### ISSUE TITLE
infinite loop in parser

### ISSUE THREAD

**Issue by mgrubb** [mrkkrp/megaparsec#104]
I'm seeing a different behavior when using megaparsec vs. parsec with regards to a recursive parser.
My code is at https://gist.github.com/090365b37ccfddb2aa37d543191e8c5a
The offender is the parseList and parseDottedList parsers.
When the program is run with the argument '(a value)' or '(a . value)' it goes into an infinite loop that I have to eventually kill -9 on the process. When compiled with Parsec 3.1.9 this behavior is not seen.
I'm very, very new to Haskell so it may just be something simple that I am missing and not a bug at all.
Any help would be appreciated.  Also, using ghc 7.10.3 on Mac OS X 10.11.4 with parsec 3.1.9 and megaparsec 4.4.0.

**Comment by mrkkrp** [comment]
The reason your program hangs when compiled with Megaparsec is that the parser `space`, as in (lines 51–52)

```haskell
spaces :: Parser ()
spaces = skipSome space
```

has different semantics from `space` from Parsec. This is because all character parsers in Megaparsec end with `Char` suffix, while in Parsec there is no such convention. `space` is Paresec is equivalent to `spaceChar` in Megaparsec, replace `space` → `spaceChar` and your program should be OK.

This may be confusing for those with Parsec background, but that's the price of consistent naming.

In Megaparsec, `space` is defined like so:

```haskell
space = skipMany spaceChar
```

This means that it will succeed even when there is no white space characters, since `skipMany p` accepts zero occurrences of `p`. Thus `space` succeeds and at the same time it does not advance parser. And because you put it in `skipSome`, it makes `skipSome` run this parser indefinitely without making any progress. This is why your parser hangs.

**Comment by mgrubb** [comment]
Thanks so much, that did the trick perfectly.
