### ISSUE TITLE
Confusion regarding some of the code

### ISSUE THREAD

**Issue by Alxandr** [mrkkrp/megaparsec#109]
Sorry about making this as an "issue", but I found no other good way to ask questions. I've been working for a short while now to convert MegaParsec to F# for several reasons. One of which is to learn how parsec works, and the other is that I cannot have any dependencies. I've currently converted all of `Pos`, `Error` and `Prim` (including tests) and everything works perfectly except one test and I don't understand why it works in the Haskell source code, so I was hoping maybe you could help me with that.

The test in question is the following:

```hs
prop_alternative_3 :: Property
prop_alternative_3 = checkParser p r s
  where p  = asum [empty, string ">>>", empty, return "foo"] <?> "bar"
        p' = bsum [empty, string ">>>", empty, return "foo"] <?> "bar"
        bsum = foldl (<|>) empty
        r = simpleParse p' s
        s = ">>"
```

Now, I've never actually done any programming in Haskell myself, except simple experimenting, but I do believe I have a reasonable understanding of the language, but I'm also guessing that my problems simply stem from my misunderstanding of the language or one of the built in functions, so I will try to show my thought process when trying to understand this test. I hope I don't bother you with elementary "anyone how knows a little bit of Haskell should know this" questions.

`asum` I've looked up hackage, and it's defined as `foldr (<|>) empty`, so I concluded that the test should be to see that the order of the parsers passed to `<|>` should not matter when considering error-messages/hints. Thus I reduced the test down to the following (still failing) test in my case:

```hs
prop_alternative_3 :: Property
prop_alternative_3 = checkParser p r s
  where p  = string ">>>" <|> return "foo" <?> "bar"
        p' = return "foo" <|> string ">>>" <?> "bar"
        r = simpleParse p' s
        s = ">>"
```

Now. `return "foo"` always calls `eok`, which `<|>` does not modify (it just passes it through to the first parser in the list), which means that effectively we can reduce `p'` to `return "foo" <?> "bar"`. `<?>` in turn (when receiving `eok`) calls `refreshLastHint` which effectively does nothing because the hint list is empty. This leaves me in a situation where `p'` resulting in `expected EndOfInput` and unexpected `>`, whereas `p` results in `expected Label "bar"` and `unexpected '>'`.

If anyone can point me to where I'm going wrong in my reasoning, I would be very appreciative :). Sorry again for asking out of place questions.

**Comment by mrkkrp** [comment]
This has to do with hints. This tests tests whether accociativity (and thus difference `foldr` vs `foldl`) has impact on result. It should not have any impact. Look carefully at how hints are organized and updated. Try to trace/print (I don't know how it's done in F#) collection of hints on every step of execution. Last time I had this very problem with Megaparsec it was because of some silly problem with how hints groups are updated. Sorry, I don't have much time to investigate and I don't know F#.

**Comment by Alxandr** [comment]
I have done that (though I don't know how to do so in Haskell). The problem (from my understanding) seems to be that `pPlus` short-circuits on `eok`.

```hs
pPlus m n = ParsecT $ \s cok cerr eok eerr ->
  let meerr err ms =
        let ncerr err' s' = cerr (err' <> err) (longestMatch ms s')
            neok x s' hs  = eok x s' (toHints err <> hs)
            neerr err' s' = eerr (err' <> err) (longestMatch ms s')
        in unParser n s cok ncerr neok neerr
  in unParser m s cok cerr eok meerr
```

It seems to me here, that if parser `m` succeeds or consumes, then the parser `n` is not invoked at all (meaning there is no way to get hints from it).

**Comment by mrkkrp** [comment]
Yes, in that case `n` is not invoked at all, because we succed (and `pPlus` only uses the second parser if the first doesn't consume). However in that test all parsers should fail.

Please note that collection of hints is a list where every element is a set. Elements of list correspond to consequent but different parsers, while sets sepresent all expected items of one parser. Note how `toHints` is coded, if we don't have expected items, we don't insert empty set (I just remember I had such a bug during refactoring).

Also note that your `p` and `p'` both return incorrect results, the correct result is:

```
λ> parseTest (p <* eof) ">>"
1:1:
unexpected '>'
expecting bar or end of input
```

Note that it makes sense because of return, we could succed with empty input:

```
λ> parseTest (p <* eof) ""
"foo"
```

I think the fact that `p` and `p'` have different parts of the correct result not joined together is a hint for you. Look how you insert existing hints into parse error (this is in the `withHints` function).

This is all I can suggest, I hope you manage to debug this.

**Comment by Alxandr** [comment]
So after using a while to figure out haskell, it turns out I found a bug:

```hs
{-# LANGUAGE ScopedTypeVariables, TemplateHaskell, FlexibleContexts #-}

module Main where

import Data.Text
import Control.Monad.Logger
import Control.Applicative

import Text.Megaparsec.Prim
import Text.Megaparsec.Error
import Text.Megaparsec.Char

p1 = ((pure "foo" <|> string ">>>") <?> "bar") <* eof
p2 = ((string ">>>" <|> pure "foo") <?> "bar") <* eof

simpleParseTest p = parse p "" ">>"

testParser :: ( Ord (Token s)
             , ShowToken (Token s)
             , Show a )
  => Parsec Dec s a -- ^ Parser to run
  -> s            -- ^ Input for parser
  -> IO ()
testParser = parseTest

--testApp :: MonadLog (WithSeverity Doc) m => m ()
--testApp = do
--  $(logDebug) (pack "test log")
--  $(logDebug) (pack "test log 2")


main :: IO ()
main = do
  putStrLn "First:"
  testParser p1 ">>"
  putStrLn ""
  putStrLn "Second:"
  testParser p2 ">>"
```

```
First:
1:1:
unexpected '>'
expecting end of input

Second:
1:1:
unexpected '>'
expecting bar or end of input
```

You want me to create a new issue?

**Comment by mrkkrp** [comment]
Well, I don't consider this a bug, because symmetry in code does not necessary mean equality in meaning. Let's take a look at your parsers and what they do.

```
p1 = ((pure "foo" <|> string ">>>") <?> "bar") <* eof
```

`(pure "foo" <|> string ">>>")`, here the first parser always succeeds, so it's the same as just `pure "foo"`. `pure "foo" <?> "bar"`, here we see use of label, but label is only visible when a parser fails — it replaces expected token in error message with given text. Since `pure "foo"` never fails, all we have is `pure "foo" <* eof`, where we can even drop `pure "foo"` if we are interested solely in error messages.

```
p2 = ((string ">>>" <|> pure "foo") <?> "bar") <* eof
```

This is completely different story because `string ">>>"` may fail. Thus its functioning is totally different, and error message too. I think it's obvious what is going on in this case and why you get this error message.

**Comment by Alxandr** [comment]
Yes. I get that. But why then is 

```hs
asum [empty, string ">>>", empty, return "foo"] <?> "bar"
```

supposed to work? This too will always hit `return "foo"` first (same as `pure "foo"`, right?). Thus, the error message should never be set, and the two should have different outputs (back to original issue).

**Comment by mrkkrp** [comment]
That's right, it will hit `return "foo"` and succeed, but it nevertheless will accumulate collection of hints that influence error message that is generated later because of `<* eof` part (implicitly added by `checkParser` and `simpleParse` helpers).

**Comment by Alxandr** [comment]
Yes. And in my case I explicitly add `<* eof` and reduce it to `asum [string ">>>", return "foo"] <?> "bar"`, shouldn't that be the same? Do the fact that there are `empty` added impact collecting of hints? Or rather; **should** it impact collecting of hints?

**Comment by mrkkrp** [comment]
No, it should not.

**Comment by Alxandr** [comment]
Then why do you think that the code I posted 2 days ago should have different outputs when it's basically the same? Or did I read your reply wrong?

**Comment by mrkkrp** [comment]
`empty` does not and should not impact collecting of hints, in your code posted 2 days ago does not use `empty` at all. I already explained why `p1` and `p2` have different semantics.

**Comment by Alxandr** [comment]
So, you're right, and it turns out it was just a giant misunderstanding on my part. I thought `foldr` was basically the same as first reversing the list and doing `foldl`. Which is obviously isn't. Therefore, I thought the test in question tested the parses in both orders. Which it doesn't.

I'm sorry for bothering you with what was essentially a non-issue all the time.

**Comment by mrkkrp** [comment]
No problem! I hope you will succeed at impelementing Megparsec in F#.

**Comment by Alxandr** [comment]
Currently all tests in `Prim` pass (I have property tests in F# as you do in Haskell based on a port of quickcheck or whatever it's called), so that's looking really good so far. Though the perf will probably be really bad.

The end goal is a new programming language, which is why I want no dependencies (so that I can later translate the parser into the new programming language). But we'll see if I ever get that far :)
