### ISSUE TITLE
Parser error when last line ends with line comment

### ISSUE THREAD

**Issue by minad** [mrkkrp/megaparsec#119]
I had to change the skipLineComment function to manyTill anyChar (lookAhead (void newline <|> eof)) 

Maybe there is another issue in my parser but this fixes the problem for me.

**Comment by mrkkrp** [comment]
In Unix every line should end with “end of line”. I think this is a good approach in general and it's also a bit faster. Nothing stops you from using your own `skipLineComment`, it's a tiny function and easily replaceable.

**Comment by minad** [comment]
I think it is reasonable to write a parser which accepts files without a final newline. At least emacs produces such files for me from time to time ;) I use my own replacement function for now but you might consider changing this? When it happend to me I was wondering if there was a bug in my parser, so it was kind of unexpected.

**Comment by user471** [comment]
Maybe `skipLineComment` could have a parameter so anyone could choose what behavior they want. Otherwise it feels weird that this function has OS specific behavior.

**Comment by mrkkrp** [comment]
It does not have OS-specific behavior. I talked about a *convention*.

**Comment by user471** [comment]
I am not a Unix expert but you said 

>In Unix every line should end with “end of line”

I use Emacs on Windows and I have same problem with this function. Why would anyone want to use such function if it cannot work with any file eof-wise?

**Comment by mrkkrp** [comment]
Normally your files have a newline at the end even on Windows machines. It's not something that has to do with OS: you can have a file without newline of the end on Unix just as well as on Windows.

Currently, definition of a *line comment* is that it ends with a *end of line* sequence (either LF (Unix style) or CRLF (Dos style) so it's quite OS-independent in this respect). You ask me to change it so line comment can end with either *end of line* or *end of file*, which is a fair request. I'm just wondering if it is so necessary and common case, because it would make things a little bit slower.

**Comment by mrkkrp** [comment]
In the meantime you can tweak definition of `skipLineComment` yourself to make it do what you want, the library does not lock you into using its version of this function. The difintion is just a one-liner and take 30 seconds to write.

**Comment by user471** [comment]
>I'm just wondering if it is so necessary and common case, because it would make things a little bit slower.

That is why I suggested parameter, so everyone could choose the function behavior.

>In the meantime you can tweak definition of skipLineComment yourself to make it do what you want, the library does not lock you into using its version of this function. The difintion is just a one-liner and takes 30 seconds to write.

Yes, but who would use this version of `skipLineComment`? Imagine someone is creating a parsing tool. Obviously this tool should support any file regardless of `newline at the end`. How can you be sure that user file always would have newline at the end?

**Comment by mrkkrp** [comment]
I use it myself without problems. I don't need to be sure, because without newline at the end that input is just malformed, and this is so rare a case that I'm just OK with that. Anyway, I got your point, this behaviour may change is future release.

**Comment by mrkkrp** [comment]
The definition of `skipLineComment` has been changed to account for the case when a line comment ends at the end of input.

**Comment by minad** [comment]
cool thx!

**Comment by liskin** [comment]
This interacts in interesting and unfortunate ways with indentation-sensitive parsing.
The "Text.Megaparsec.Lexer indentBlock IndentMany works as intended" test succeeds with "aaa\n//test\n" but it does not parse "aaa\n//test" since skipLineComment skips to column 6 of line 2 and indentBlock interprets that as a bigger indent and expects to parse "bbb" there. If this change was reverted, skipLineComment would fail the parse with unexpected end of input and there'd be no confusion.

But it may be better to teach intentBlock/indentGuard that there's no point in looking at indentLevel at end of input. But I don't know -- today's the first time I'm using megaparsec. :-/

**Comment by liskin** [comment]
diff --git a/tests/Text/Megaparsec/LexerSpec.hs b/tests/Text/Megaparsec/LexerSpec.hs
	index 2cd9c74..334f54f 100644
	--- a/tests/Text/Megaparsec/LexerSpec.hs
	+++ b/tests/Text/Megaparsec/LexerSpec.hs
	@@ -186,7 +186,7 @@ spec = do
				  | otherwise -> prs p s `shouldParse`
					(sbla, [(sblb, [sblc]), (sblb, [sblc])])
		 it "IndentMany works as intended" $
	-      property $ forAll (mkIndent sbla 0) $ \s -> do
	+      property $ forAll ((<>) <$> mkIndent sbla 0 <*> mkWhiteSpaceAtEof) $ \s -> do
			 let p    = lvla
				 lvla = indentBlock scn $ IndentMany Nothing (l sbla) lvlb <$ b sbla
				 lvlb = b sblb
	@@ -428,6 +440,9 @@ mkWhiteSpace :: Gen String
	 mkWhiteSpace = concat <$> listOf whiteUnit
	   where whiteUnit = oneof [whiteChars, whiteLine, whiteBlock]
	 
	+mkWhiteSpaceAtEof :: Gen String
	+mkWhiteSpaceAtEof = oneof [mkWhiteSpace, whiteLineAtEof]
	+
	 mkSymbol :: Gen String
	 mkSymbol = (++) <$> symbolName <*> whiteChars
	 
	@@ -454,6 +469,10 @@ whiteLine = commentOut <$> arbitrary `suchThat` goodEnough
	   where commentOut x = "//" ++ x ++ "\n"
			 goodEnough x = '\n' `notElem` x
	 
	+whiteLineAtEof :: Gen String
	+whiteLineAtEof = stripEol <$> whiteLine
	+  where stripEol s = let '\n':s' = reverse s in reverse s'
	+
	 whiteBlock :: Gen String
	 whiteBlock = commentOut <$> arbitrary `suchThat` goodEnough
	   where commentOut x = "/*" ++ x ++ "*/"

**Comment by liskin** [comment]
Actually the test is falsifiable with mkWhiteSpace, too, on `"aaa\n/*test*/"`. Not sure what to do with that. :-(

**Comment by mrkkrp** [comment]
If we decide to keep the present behavior, we should at least document it. This weekend I may have time to think about proper solution though. Thanks @liskin for pointing this out.
