### ISSUE TITLE
Problem with expression parser

### ISSUE THREAD

**Issue by user471** [mrkkrp/megaparsec#129]
I want to support two operators "+" and "++"
```
data Expr =
  Add Expr Expr |
  Append Expr Expr |
  Ident String
  deriving (Eq, Ord, Show)

ident :: Parser Expr
ident = Ident <$> lexeme (some lowerChar)

op = [
  [ Ex.InfixN (try (rword "++") *> return Append)],
  [ Ex.InfixN (try (rword "+") *> return Add)]
     ]

expr = Ex.makeExprParser ident op
```
I can parse `x + y` and `x ++ y`
But if I change operators' precedences
```
op = [
  [ Ex.InfixN (try (rword "+") *> return Add)],
  [ Ex.InfixN (try (rword "++") *> return Append)]
     ]
```
I cannot parse `x ++ y`

>1:4:
>unexpected '+'
>expecting lowercase letter

I tried same with Parsec and It looks like it doesn't have this problem.

**Comment by mrkkrp** [comment]
How `rword` is defined?

**Comment by user471** [comment]
from the tutorial
```
rword :: String -> Parser ()
rword w = string w *> notFollowedBy alphaNumChar *> sc
```

**Comment by mrkkrp** [comment]
I can see why this happens and I know how to fix it, but I don't know why Parsec works with it. I'll look into this behavior later today and update.

**Comment by mrkkrp** [comment]
> I tried same with Parsec and It looks like it doesn't have this problem.

I'm getting the same result with Parsec. Please provide source code that uses Parsec and behaves differently than Megaparsec version you provided. Thanks.

**Comment by mrkkrp** [comment]
Actual feedback regarding your parser:

* You don't need `rword` unless names of your variables can start with punctuation line `+`. Use `symbol` instead. `rword` is for alphanumeric sequences that are not names of variables. The `notFollowedBy alphaNumChar` part ensures that your reserved word is not prefix of some variable. In the case with `+` this check is redundant.

* When you use `symbol` (or indeed `rword`), you don't need a `try`, because these are built on `string`, which backtracks by default in recent versions of Megaparec.

* You can use `Add <$ symbol "+"` instead, `<$` is quite nice in this case.

In the case you report (when `+` has higher precedence), the parser tries operators in turn and `+` obviously succeeds and consumes the first `+` of the two. Then the parser tries to continue (for that it needs a term, `Ident`), but it only sees another `+` and thus fails.

In this particular case, you need to make your `Add <$ symbol "+"` parser fail if it runs into two plus signs in a row. This is how you do it:

```haskell
Add <$ (notFollowedBy (string "++") *> symbol "+")
```

This should resolve you issue.

**Comment by user471** [comment]
```
lexer :: Tok.TokenParser ()
lexer = Tok.makeTokenParser style
  where
    style = emptyDef {Tok.identStart = lower , Tok.identLetter    = alphaNum}
reservedOp :: String -> Parser ()
reservedOp = Tok.reservedOp lexer



identifier = Tok.identifier lexer


data Expr =
  Add Expr Expr |
  Append Expr Expr |
  Ident String
  deriving (Eq, Ord, Show)

ident :: Parser Expr
ident = Ident <$> identifier



table = [
 
  [Ex.Infix (reservedOp "+" >> return (Add)) Ex.AssocLeft],
  [Ex.Infix (reservedOp "++" >> return (Append)) Ex.AssocLeft]
  ]
expr :: Parser Expr
expr = Ex.buildExpressionParser table ident
```

**Comment by user471** [comment]
>This should resolve you issue.

Is there any more generalized way?

I have feature similar to Haskell "infix" notation so there could be a dozens of different operators.

**Comment by user471** [comment]
>In the case you report (when + has higher precedence), the parser tries operators in turn and + obviously succeeds and consumes the first + of the two.

But I use `try`. Shouldn't it try next operator after fail?

**Comment by mrkkrp** [comment]
> But I use `try`. Shouldn't it try next operator after fail?

`rword "+"` does not fail, and the next operator alternative is never tried. You seem to have wrong understanding of what `try` does. See [our docs](https://hackage.haskell.org/package/megaparsec-5.0.1/docs/Text-Megaparsec.html#v:try) for explanation.

----

Now try with Parsec this way:

```haskell
symbol :: String -> Parser String
symbol str = string str <* many space

…

table = [

  [Ex.Infix (symbol "+" >> return Add) Ex.AssocLeft],
  [Ex.Infix (symbol "++" >> return Append) Ex.AssocLeft]
  ]
```

This is more precise equivalent of Megaparsec code. This behaves exactly the same. The difference in `reservedOp` wrapper which is doing:

```
reservedOp name =
    lexeme $ try $
    do{ string name
      ; notFollowedBy (opLetter languageDef) <?> ("end of " ++ show name)
      }
```

And this is how you resolve your problem is a more general way. You need to ensure that your operator is not followed by other characters that may belong to operators. Note that if you use this approach, you will need to wrap entire thing is `try` (because `string` may succeed and consume and then `notFollowedBy` part may fail).

**Comment by user471** [comment]
Thanks.

**Comment by user471** [comment]
Another small question. What would be the best way to handle undefined operators?
For example if I try to parse `1 * 2` the error is
```
unexpected '1'
expecting lowercase letter
```
But I want something like `operator * is not defined`

**Comment by mrkkrp** [comment]
You are getting this error because your parser does not accept numbers as terms, only variables. Here is what I get with variables:

```haskell
λ> parseTest (expr <* eof) "x * y"
1:3:
unexpected '*'
expecting end of input or operator
```

This looks good to me. You need to construct a parser for terms that would include numbers as well as identifiers and then use it as the first argument of `makeExprParser`.

**Comment by user471** [comment]
Sorry, my mistake.
Yes I mean this
```
"x * y" 
1:3: unexpected '*' 
expecting end of input or operator
```
It's not bad, but I want a better error message.
```
operator * is not defined
```
Is it possible?

**Comment by mrkkrp** [comment]
Yes, this is possible. Take a look at [this section](https://mrkkrp.github.io/posts/announcing-megaparsec-5.html#well-typed-and-customizable-error-messages) of my blog post announcing Megaparsec 5. Basically you need to define an alternative of built-in `Dec`, add to it a constructor that would represent undefined operator, define how to pretty print that stuff and then place `failure`-based parser at the end of list in the operator table. That parser would grab a row of punctuation characters and always fail reporting it.

Sorry I don't have time to write an example, but it should be pretty easy to do.

**Comment by user471** [comment]
Thanks

**Comment by user471** [comment]
I ended up with this solution
```
reservedOps = ["->", ":",  "|",  "="]
opChar = oneOf "!#$%&*"
reservedOp o = string o *> notFollowedBy opChar *> sc

operator = lexeme $ some opChar

notDifinedOperatorParser = do
  reservedOps & traverse_ (notFollowedBy . reservedOp)
  x <- operator
  fail $  x ++ " is not defined"
```
I can add `notDifinedOperatorParser` to the last position and it will parse any operator that is not difined.
```
operators :: [[Operator Parser Expr]]
operators =
  [
   ......
   [Ex.InfixN anyOperatorParser]
  ]
```

Is there anything wrong with it?
I am not sure about this code
```
 reservedOps & traverse_ (notFollowedBy . reservedOp)
```

**Comment by user471** [comment]
@mrkkrp 

I ended up with this solution
```
reservedOps = ["->", ":",  "|",  "="]
opChar = oneOf "!#$%&*"
reservedOp o = string o *> notFollowedBy opChar *> sc

operator = lexeme $ some opChar

notDifinedOperatorParser = do
  reservedOps & traverse_ (notFollowedBy . reservedOp)
  x <- operator
  fail $  x ++ " is not defined"
```
I can add `notDifinedOperatorParser` to the last position and it will parse any operator that is not difined.
```
operators :: [[Operator Parser Expr]]
operators =
  [
   ......
   [Ex.InfixN anyOperatorParser]
  ]
```

Is there anything wrong with it?
I am not sure about this code
```
 reservedOps & traverse_ (notFollowedBy . reservedOp)
```

**Comment by mrkkrp** [comment]
@user471 I see your message, I'll answer on the weekend.

**Comment by mrkkrp** [comment]
@user471 If you use `notDefinedOperatorParser` as your last alternative, all defined parsers have been tried and rejected by the time parser gets to `notDefinedOperatorParser`, thus you don't need to repeatedly call `notFollowedBy` (that will also get slow pretty fast). Just grab a row of `orChar`s and report it.

**Comment by user471** [comment]
@mrkkrp 
But some operators aren't in operator table and aren't used in makeExprParser
for example "->"
```
lambda = do
  L.rword "fun"
  params <- parseParams
  reservedOp "->"
  body <- parseBody
  return $ Lambda params body
```
So, without ` ["->", ":", "|", "="] & traverse_ (notFollowedBy . reservedOp)`
`notDifinedOperatorParser ` parses operator "->" as undefined

**Comment by mrkkrp** [comment]
OK, now that you gave more context of what you are trying to achieve, your code makes more sense. I guess it's OK, although I would write it as:

```haskell
mapM_ (notFollowedBy . reservedOp) reservedOps
```

**Comment by user471** [comment]
thanks
