### ISSUE TITLE
How to define identifier parser similar to Parsec

### ISSUE THREAD

**Issue by user471** [mrkkrp/megaparsec#141]
Here is a Parsec parse that can parse expression `let foo = bar x in foo`
```
Right (Let "foo" (Apply "bar" ["x"]) (Var "foo"))
```

```
import Text.Parsec
import Text.Parsec.String (Parser)
import Text.Parsec.Language (emptyDef)
import Prelude

import qualified Text.Parsec.Expr as Ex
import qualified Text.Parsec.Token as Tok

reservedOp :: String -> Parser ()
reservedOp = Tok.reservedOp lexer

lexer :: Tok.TokenParser ()
lexer = Tok.makeTokenParser style
  where
    style = emptyDef {Tok.identStart = lower , Tok.identLetter    = alphaNum, Tok.reservedNames = ["let", "in"]}



identifier = Tok.identifier lexer
reserved = Tok.reserved lexer

data Expr =
  Var String |
  Apply String [String] |
  Let String Expr Expr
  deriving (Eq, Ord, Show)

var :: Parser Expr
var = Var <$> identifier


apply = Apply <$> identifier <*> many1 identifier

letExpr = do
  try $ reserved "let"
  name <- identifier
  reserved "="
  val <- try apply <|> var 
  reserved "in"
  body <- expr
  return $ Let name val body


expr = letExpr <|> try apply <|> var

parseExpr s = parse (expr <* eof) "" s
```
and here MegaParsec parser
```
import Text.Megaparsec
import Text.Megaparsec.String
import Prelude
import Control.Monad
import qualified Text.Megaparsec.Lexer as L
import Control.Applicative
import Text.Megaparsec.Expr as Ex

lineComment :: Parser ()
lineComment = L.skipLineComment "--"

scn :: Parser ()
scn = L.space (void spaceChar) lineComment empty

sc :: Parser ()
sc = L.space (void $ oneOf " \t") lineComment empty


lexeme :: Parser a -> Parser a
lexeme = L.lexeme sc

reserved :: String -> Parser ()
reserved w = string w *> notFollowedBy alphaNumChar *> sc

rws = ["let", "in"]

identifier :: Parser String
identifier = lexeme (p >>= check)
  where
    p       = (:) <$> letterChar <*> many alphaNumChar
    check x =
      if x `elem` rws
      then fail $ "keyword " ++ show x ++ " cannot be an identifier"
      else return x

data Expr =
  Var String |
  Apply String [String] |
  Let String Expr Expr
  deriving (Eq, Ord, Show)

var :: Parser Expr
var = Var <$> identifier


apply = Apply <$> identifier <*> some identifier

letExpr = do
  try $ reserved "let"
  name <- identifier
  reserved "="
  val <- try apply <|> var
  reserved "in"
  body <- expr
  return $ Let name val body


expr = letExpr <|> try apply <|> var

parseMega = parseTest (expr <* eof)
```
but it cannot parse `let foo = bar x in foo` bacause of `in` keyword
```
1:15:
unexpected 'x'
expecting "in"
```
The difference is in identifier parser
identifier from `Parsec`
```
    identifier =
        lexeme $ try $
        do{ name <- ident
          ; if (isReservedName name)
             then unexpected ("reserved word " ++ show name)
             else return name
          }
```
1) How to recreate it in `MegaParsec`?
`unexpected` has weird type `ErrorItem (Token s) -> m a`
2) What is the reason the tutorial use `fail` instead of `unexpected`?

**Comment by user471** [comment]
Any suggestion?

**Comment by mrkkrp** [comment]
Why do you import `Prelude` explicitly?

Why `try $ reserved "let"`? You can remove `try` in Megapasec version. Actually you want `try` around `letExpr` in `expr`. The effect is the same, but it will be clearer in code where you want to backtrack.

To answer your questions:

1. Let's see what is going on. `apply` starts to parse identifiers, so it grabs `"bar"`, then `"x"`, then `"in"`, but before returning the `"in"` `identifier` it says “Wait a minute! This cannot be an identifier!” and so it fails (using `fail`), *but input has been consumed and `some` has to fail completely instead of just stopping parsing the row of identifiers*, and since `apply` is wrapped in `try` we return to beginning of `"bar"` again. `var` gets its chance now. It parses `"bar"` all right and finishes. Now you try to pick up `"in"`, but what you have next in input is `"x"`, hence the parse error.

   Why does it work is Parsec then? What's the difference? The difference is that `identifier` is Parsec is wrapped in `try`, so even when it fails (as with `fail` in our case), it backtracks and `some` just stops there.

   The solution is to add `try` to definition of `identifier`:

   ```haskell
   identifier :: Parser String
   identifier = (lexeme . try) (p >>= check)
     where
       p       = (:) <$> letterChar <*> many alphaNumChar
       check x =
         if x `elem` rws
         then fail $ "keyword " ++ show x ++ " cannot be an identifier"
         else return x
   ```
2. This tutorial is derived from an older tutorial written for Parsec, and Parsec has nothing better than `fail` for custom error messages. `unexpected` would not be as nice here, because it would not explain that the thing is not just unexpected, but this string cannot be an identifier. The `fail` function is used for clearer error message.

----

I'll add mention of this behavior to docs of `many` (`some` is defined via `many`) and also explain this moment in the tutorial and update it to use `try` as well.

Thank you for opening the issue! I have limited free time these days, so I could not answer immediately.

**Comment by mrkkrp** [comment]
Done, I updated the docs and the tutorial.

**Comment by user471** [comment]
thanks
>Why do you import Prelude explicitly?

NoImplicitPrelude
>Why try $ reserved "let"? 

I read about it http://blog.ezyang.com/2014/05/parsec-try-a-or-b-considered-harmful/

It feels weird that parser with fail result consume input.

>but input has been consumed and some has to fail completely instead of just stopping parsing the row of identifiers

Why should `some` fail completely in this case?

**Comment by mrkkrp** [comment]
“Try a or b considered harmful” does not quite apply to Megaparsec. It's better than Parsec in error reporting. See here: https://notehub.org/w7037.

> It feels weird that parser with fail result consume input.

You first consume some characters then you use `fail`, the parser `identifier` as a whole consumes input and failes. `fail` sure doesn't consume anything.

> Why should some fail completely in this case?

We do not backtrack automatically everywhere because it would make performance worse (backtracking is expensive). Given that, if your `p` from `some p` fails consuming input, what else could we possibly do? `p` has already incremented parsing position, and we cannot backtrack by default, we have to fail.

**Comment by mrkkrp** [comment]
BTW, technically, you don't need `try` around `reserved "let"` and around `letExpr` as well. `string` backtracks automatically in versions 4.4.0+.

**Comment by albertnetymk** [comment]
Based on the update doc, the following works fine:

```
if true then
  skip
else
  skip
```
However, removing `true` gives me this error:

```
1:8:
keyword "then" cannot be an identifier
```
With the backtracking, I was expecting the position to be 1:4. After adding `<?> "bexpr"` to `bTerm`, the error msg is improved, IMO, to be sth like "expecting bexpr". Still, the cant-be-an-identifier error msg is a bit user-unfriendly.
