### ISSUE TITLE
Docs not up to date?

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#153]
I saw a difference in types in the documentation and when i clicked on Source

https://hackage.haskell.org/package/megaparsec-5.1.2/docs/Text-Megaparsec.html#t:Parsec

https://hackage.haskell.org/package/megaparsec-5.1.2/docs/src/Text-Megaparsec-Prim.html#Parsec

**Comment by mrkkrp** [comment]
Good catch, the docs are up to date, but the linked source certainly is not. I had to upload the docs manually because Hackage does not work properly with respect to generation of docs, so I used the `neil` utility with Cabal sandboxing. I'm not sure how to fix the linked source. Please use Stackage instead whenever possible:

https://www.stackage.org/nightly-2016-11-19/package/megaparsec-5.1.2

It works correctly:

https://www.stackage.org/haddock/nightly-2016-11-19/megaparsec-5.1.2/src/Text.Megaparsec.Prim.html#Parsec

You you (or anyone else) happen to know how to fix the sources that Haddock shows, there will be no delay on my part.

**Comment by mrkkrp** [comment]
Thanks to Hackage gods, the new release got proper auto-generated docs. I think there is no reason to keep this open any longer.
