### ISSUE TITLE
many should accepts parsers which consume no input and return zero-times

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#159]
I'm just going to link to this comment for the moment https://github.com/mrkkrp/megaparsec/issues/122#issuecomment-269133846

I will edit this first posts if i need to provide some more clarity.

**Comment by mrkkrp** [comment]
> I think there is a problem with this check because "many times consume no
> input" should resolve to "0 times".

Why?

----

The current situation with `many` is a consequence of two facts:

1. Parser that does not consume also does not advance parser state.
2. `many` per definition is going to try its argument parser til it fails.

Since the parser that does not consume also succeeds (otherwise it the whole thing would finish), `many` would try running it indefinitely, which is most probably a programming mistake.

I can't say I love this `error` thing very much, it's pretty ugly. But the current behavior is at least logical and consistent with respect to the rest of the library. What you propose is a completely arbitrary change that I suspect may create just more bugs.

You consider:

```
a ::= b*
b ::= c*
```

But for `many` (and other parsers in Megaparsec) `b` is indistinguishable (and this is good, we don't want to know too much about inner parsers) from other thing `e` which also succeeds on empty input. What if:

```haskell
e = do
  n <- get
  if n < 10
    then modify (+ 1)
    else empty
```

This is arbitrary, but perfectly valid monadic code that will count to 10 every time consuming nothing and then fail. Speaking of this, we probably could allow code that does not consume any input and remove the `error` at the risk of running into non-termination bugs (which are possible to introduce in other ways, there is no panacea against this), but we should not introduce ad-hoc logic here.

**Comment by mrkkrp** [comment]
It's like you're saying that you deduce `n` from this

```
0 = n * 0
```

as being equal to zero, when in fact it may be anything, even ∞.

**Comment by flip111** [comment]
Yes zero is always a weird edge case :) Consider you want to get an average of an array. Let's say the sum is 12. And you have two elements `12 / 2 = 6`, now you have one element `12 / 1 = 12`. Fractional numbers are not allowed, but let's pretend they are `12 / 0.5 = 24` .. you can see that when length approaches zero the average should go to infinitive. HOWEVER when length is 0 you will stop using this formula and instead make an edge case like so:

```
if len = 0 then
  return 0;
else
  return sum / len;
end if
```
(in pseudo code)

Ok now back to the parser. You established two rules and their consequence

> Since the parser that does not consume also succeeds (otherwise it the whole thing would finish), many would try running it indefinitely, which is most probably a programming mistake.

Now the logic that we need is this

```
IF argument_parser = fail THEN
  return Fail;
ELSE
  IF consumed = 0 THEN
    return Success;
  ELSE
    // run again to find more elements
  END IF
END IF
```

In the example you raise about the `+10 monad` seems to me it's not pure code anymore and contain some state. Yes i see in that case changing the logic would break this :) With `many` the control stays with the argument parser as long as it doesn't fail. What about if we introduce a new parser that returns control according to the pseudo code snippet above?

By the way isn't it possible to encode in the types if you are dealing with code that possibly doesn't halt? I think the distinction between pure code and monadic code is quite big here. Perhaps it's possible to account for that? I take it with pure code you can apply the logic above without any further constraints as the result will be the same each time you call the argument parser so `many` does not have to try again if it sees that there was nothing consumed already the first time.

**Comment by mrkkrp** [comment]
> HOWEVER when length is 0 you will stop using this formula and instead make an edge case like so

If total sum is 12 still, why would I say that average is 0? This is absolutely arbitrary.

> By the way isn't it possible to encode in the types if you are dealing with code that possibly doesn't halt

Possible, but not convenient, it's a lot of bookkeeping to be done on type level, and it's not going to play well with other parts Haskell system. I.e. if we differentiate at type level between parsers that may not consume input and others, we wouldn't be able to use `sequence` for example without existential wrappers, etc. It's just too much overhead everywhere.

Monadic code is pure :-) About state: parser itself has state, I could change tab width instead of abstract number. That would be valid code and it should work.

You can try to implement the new combinator and open a PR.

**Comment by flip111** [comment]
> If total sum is 12 still, why would I say that average is 0? This is absolutely arbitrary.

If you have length 0, then you can not have sum 12 either, because you are not summing anything anymore ;)

> About state: parser itself has state, I could change tab width instead of abstract number. That would be valid code and it should work.

I don't understand what you are saying here about tab width.

> it's a lot of bookkeeping to be done on type level

I was thinking perhaps it can already be inferred somehow without wrapping everything in newtype's. Anyway i've read the edge of my current knowledge ... might get back to this in a few months or years.

> You can try to implement the new combinator and open a PR.

Nice :)

**Comment by mrkkrp** [comment]
Tab width is core part of parser even without `State` or `StateT`, that's why I mentioned it.

**Comment by mrkkrp** [comment]
Closing this right now, feel free to miplement the new combinator and open a PR.

**Comment by flip111** [comment]
I'm a bit stuck with making the new combinator. I choose position to check if the parser has consumes anything, but maybe there are better ways to check this. Below is a piece of code that shows my idea but doesn't compile yet. Could you take a look at this piece of code and give some feedback so that i know i'm thinking in the right direction??

```haskell
many2 p = do
  pos <- M.getPosition
  p >>= \x -> case r of
    Left x -> Left x
    Right x -> do
               pos2 <- M.getPosition
               if pos == pos2 then
                 return Right []
               else
                 case many2 p of
                   Left _ -> return $ Right [x]
                   Right y -> return $ Right x : y
```

Here is another way with unfoldWhileM but i'm not sure if it will work. Note that `Either String Int` should become another type something with ErrorMessage or so ..

```haskell
type IntermediateResult = (Either String Int, SourcePos, SourcePos)

check :: IntermediateResult -> Bool
check (_, p1, p2) = p1 /= p2

step = do
  pos1 <- M.getPosition
  x <- p
  pos2 <- M.getPosition
  return (x, pos1, pos2)

getPs :: m [IntermediateResult]
getPs = unfoldWhileM check step

result = sequence . map fst <$> getPs
```

**Comment by mrkkrp** [comment]
Ah, you're writing it on wrong level of abstraction. You need to write it using low-level continuation stuff as in `Text.Megaparsec.Prim`. That said, I'm hesitant to recommend you to continue work on that level, because I'm not sure how useful this will be. Still feels like a very ad-hoc and confusing solution to me.

Maybe you could describe what problem you're trying to solve instead, and we could figure out how to do it with existing tools?

**Comment by flip111** [comment]
When i was typing my answer, to give a good example, i noticed there is actually a mistake in my grammar. I still know the purpose of this combinator, but now i don't have a good use case for it anymore :confounded:

If i run into needing this combinator again i will give the use case at that time. Thanks for thinking along nevertheless.

**Comment by flip111** [comment]
Ok i have a good test case now. This is a typical situation where i run into while developing the parser. Just long loops that cause severe slowdowns and extremely difficult to find out which combination of rules cause this.

I expect `DF [DU (CC [])]` to be returned for empty input `""`.

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS -Wall #-}

module Main where

import Control.Applicative
import qualified Text.Megaparsec as M
import Text.Megaparsec.Text

data P_A = DF [P_B] deriving (Eq, Show)
p_A :: Parser P_A
p_A = M.dbg "A" $ DF <$> (some p_B)

data P_B = DU P_C deriving (Eq, Show) -- second data field will be added later
p_B :: Parser P_B
p_B = M.dbg "B" $ DU <$> p_C

newtype P_C = CC [P_D] deriving (Eq, Show)
p_C :: Parser P_C
p_C = M.dbg "C" $ CC <$> (many p_D)

data P_D = Lib P_E deriving (Eq, Show)
p_D :: Parser P_D
p_D = M.dbg "D" $ (Lib <$> p_E)

data P_E = LC String deriving (Eq, Show)
p_E :: Parser P_E
p_E = M.dbg "E" $ LC <$> M.string' "dummy"

main :: IO ()
main = putStrLn "hello"

bug :: Either (M.ParseError Char M.Dec) P_A
bug = M.parse (p_A <* M.eof) "" ""
```
