### ISSUE TITLE
Do not hide constructors

### ISSUE THREAD

**Issue by wdanilo** [mrkkrp/megaparsec#167]
Hi!
You should never hide constructors, like `ParsecT(ParsecT)` and export eerything if somebody want to hack it. I need to implement custom mapping that will handle rankNtypes and I cannot because the constructor is hidden. things that should not be imported by end-users in normal way just put into some Internal modules.

**Comment by mrkkrp** [comment]
> You should never hide constructors, like ParsecT(ParsecT) and export eerything if somebody want to hack it.

Thanks for trying to educate me, but I happen to have a different opinion on this. Implementation details should be hidden and inaccessible. It's as if you tell me to export normal constructors along with smart constructors to facilitate *hacking*. “Internal” modules also typically expose things that should not be seen by users. I usually try my best to avoid public internal modules.

If you want to get this deep, then perhaps the library is not flexible enough/lacking important features, or you're over engineering/doing something wrong. If you give me an example of what you trying to do in code, then perhaps we can discuss how to better approach it.

**Comment by wdanilo** [comment]
@mrkkrp my message was not offensive in any way, I don't "try to educate you". Anyway community should educate itself constantly. 

However, I don't think you are right here. Why library should not give access to its internals for users that are powerfull enough to be able to hack it / tests the hacks etc? Every major Haskell library is done this way, look for example at lens one: https://hackage.haskell.org/package/lens

In my case the problem is very simple. I've got:
```
newtype Foo a = Foo (forall m. M m => m a)
test :: M m => Parser (m a)
```
I want to have a function with signature `forall a. (forall M m => Parser m a) -> Parser (Foo a)`.
It cannot be done using functors and other exposed methods, unless I'm not aware of some rankN inference trick.

**Comment by wdanilo** [comment]
Another example is the Lexer's `sign` function. I dont want to parse space after the sign, so I dont want to use the only exported `signed` function. Of course I can provide to it the first arg of `return ()` buts its a little ugly and could affect performance. Asking for each such change is a little bit tedious, so allowing users to just access the functions would be much better choice.

**Comment by mrkkrp** [comment]
> Every major Haskell library is done this way, look for example at lens one

This does not mean it's the only right way to do it. All this stuff is opinionated. Every major Haskell library uses `int` for length, tell me this is right…

> Another example is the Lexer's sign function

It's trivial to rewrite just `signed` function. The idea of lexer module is that it doesn't lock you into anything, every single function is simple to re-implement if necessary with any desired changes, you can still use the others.

There are two things: ability to hack and redundancy that may confuse user. The latter is a big evil, IMO. I'm of the opinion that API should provide only things that user will certainly need, it should not expose any inner details, because they may be confusing, especially to beginner. The less we expose, the simple it is to maintain and change without breaking something. My “best” libraries (those that I consider good) expose only 3–5 well-documented functions and beginners seem to like this straightforward approach that always gets them a working solution in no time. Most major Haskell libraries are hairy on the other hand, it's well known that it's hard to start with most of them.

So yes, I do question authorities here and I do think that many major libs could benefit from different API. Closing, sorry, I have very strong opinion about this matter that is unlikely to change.
