### ISSUE TITLE
The tutorial should start with an even easier task

### ISSUE THREAD

**Issue by alexanderkjeldaas** [mrkkrp/megaparsec#168]
The tutorials are good, but it shouldn't start with "parsing a simple language".  Rather it should start with "parsing a simple log file", and then advance to a simple language.

Why?  Spending 5-10 minutes reading about parsing a simple language is wasteful when 90% of quick-and-dirty parsing is about parsing much simpler things.

**Comment by mrkkrp** [comment]
This is a valid request. Just keep in mind that tutorials are sorted by the date of last modification, so if you see “Parsing a simple imperative language” going first, it's just because it was recently modified.

**Comment by mrkkrp** [comment]
Do you want to contribute such a tutorial? It's unlikely that I'll have the time to write in near future.

**Comment by hardvain** [comment]
I am a haskell newbie and I would like to learn haskell by working with some well established libraries and this seems to be a very good one. I would like to start by learning megaparsec and I feel in that process, I can contribute to this issue. Any pointers are welcome.

**Comment by mrkkrp** [comment]
Hey @hardvain, you are certainly most welcome to write a tutorial that starts with an easier task. I thought about this myself, but got distracted and later decided to use my drafts in a chapter about Megaparsec in this book: https://intermediatehaskell.com.

I can't give any pointers what to write about though. I'd advise picking a simple format that you use yourself or find interesting and show key features of the library writing a small parser for that format. Branching and backtracking should be certainly covered, as well as functions like `string` and `char` that are most common.

I can review your tutorial and either host it with the rest of the tutorials on my site or add a link to your tutorial so the users can find it. Best of luck :-)

**Comment by jaseemabid** [comment]
I found the error handling to be way more complicated and went back to parsec after fighting it for a few hours. I read through all the blogs and haddock.

1. Need simpler docs. I just needed a custom Error type and the docs/examples doesn't help at all. 
2. Simple things should be simple. I think the library is forcing a bit too much on users. All the error machinery is not required when most people start things up. A more gradual approach would have been so much better. For example I was hoping to find some function like parsec's 'parserFail', but it took me down a very deep rabbit hole of 
1) failure function 
2) adding an Ord to my old Error type 
3) Make Error an instance of ShowErrorComponent 
4) Understand TrivialError 
5) Custom type wrapper with source position etc etc etc.

**Comment by mrkkrp** [comment]
Hi @jaseemabid, I sincerely appreciate your input. However it looks like you're comparing completely different functionality. With `parserFail` you fail with just a `String`. Actually `parserFail` should not be public in Parsec because it's the same as `fail`. With `fancyFailure` you fail with *anything you like*. Nothing prevents you from using `fail` function with Megaparsec (reporting a `String` just like with `parserFail`). Thus Megaparsec allows you to do the same things as Parsec plus more.

I'd like to point out that many libraries may seem over-engineered at first just because it's not obvious how many consideration and use cases they try to address (because your use-case is different). The situation is just like with programming languages, remember the blub paradox:

> As long as our hypothetical Blub programmer is looking down the power continuum, he knows he's looking down. Languages less powerful than Blub are obviously less powerful, because they're missing some feature he's used to. But when our hypothetical Blub programmer looks in the other direction, up the power continuum, he doesn't realize he's looking up. What he sees are merely weird languages. He probably considers them about equivalent in power to Blub, but with all this other hairy stuff thrown in as well. Blub is good enough for him, because he thinks in Blub.

I think the current design is the best design we've had since beginning. Of course nothing is perfect and  I'm open to discussion.

> Need simpler docs

Would you like to help improve the docs?

**Comment by sshine** [comment]
> Would you like to help improve the docs?

I would. It seems that some tutorials out there are incompatible with 6.x, e.g. [Akash Agrawal's](http://akashagrawal.me/beginners-guide-to-megaparsec/) referring to `Text.Megaparsec.String`. I really like it because it starts with the basics (what `stack` is, how combinators work). Maybe I'll do one that solves simple regex-like tasks and proceeds to parse a log format, as someone suggested.

**Comment by mrkkrp** [comment]
Feel free to give it a go! There was some work on a unified (and pretty long) tutorial that I made for 
 the [Intermediate Haskell](https://intermediatehaskell.com/) book. But it looks like everyone who worked on the book got busy with their jobs, etc., and the effort has stagnated. That's a shame, there is still a very good writing there waiting to be published.

**Comment by mbwgh** [comment]
I'd like to chime in and suggest that maybe something like a FAQ would be nice to have as well.
In particular, it should address typical beginner mistakes. Examples:

* Overlapping character starving follow-up parsers:

```haskell
type Parser = Parsec Void String

-- "abcxe" -> "abc", as expected
test1 :: Parser String
test1 = anyChar `manyTill` char 'x'

-- "hello, world" -> ["hello, world"], not ["hello", " world"]
test2 :: Parser [String]
test2 = some anyChar `sepBy` char ','
```

* Non-termination issues

```haskell
-- "hello world" -> ["hello world"] (stupid but terminates)
test3 :: Parser [String]
test3 = many word
  where word = some anyChar

-- "hello world" -> <loop>
test4 :: Parser [String]
test4 = many word
  where word = many anyChar
```

* How does quick and dirty ad-hoc parsing differ from parsing some well-structured format?
* What kind of character sets should one prefer? For example, in a `sepBy` context, should I parse tokens using `noneOf`? How should I parse these emails then:

```
To: Dr. Good <good@heaven.org>, "Evil, Dr. <haha@haha.ha>" <evil@hell.com>, "nöbräckets"@example.com
```

There are probably other more obvious caveats as well, but of course once you have some routine you eventually forget what you were struggling with initially.

**Comment by mrkkrp** [comment]
I'm going to close this because I see clearly that it's not possible for me to find time and write yet another tutorial. I'll concentrate on working on the library itself, its docs, and keeping the existing tutorials up to date.

If you think that a different tutorial is necessary, you could as well... write it. And I can add a link to it to the readme. Hope this is fair!
