### ISSUE TITLE
Parser function for Text

### ISSUE THREAD

**Issue by flip111** [mrkkrp/megaparsec#172]
There is a Parser type to store Text, but i didn't find a parser function to parse and yield Text. At the moment i'm doing something like `text t = T.pack <$> M.string' (T.unpack t)`, is this perhaps something that could be added to the library?

**Comment by mrkkrp** [comment]
This could be added, but then we would have to add at least two combinators for each built-in stream type (strict and lazy text, strict and lazy byte strings). This is 8 new functions that are ad-hoc and pure boilerplate. Feels like the library will start to provide redundant combinations of building blocks, instead of just providing the blocks. I'd prefer to leave defining these things to users, it's not hard, is it?

**Comment by flip111** [comment]
Ok good point. I wonder though does the casting between Text and String loose some performance? Could the `M.string'` function be implemented more efficiently if it doesn't have to use String as intermediate format?

**Comment by mrkkrp** [comment]
See here, it has been discussed previously: https://github.com/mrkkrp/megaparsec/issues/106.

**Comment by flip111** [comment]
Ok another good point :P Maybe worth adding a note in the readme since it keeps coming up. I think [this](https://github.com/mrkkrp/megaparsec/issues/106#issuecomment-228581199) looks like an interesting solution if more performance is needed. About implementing 8 different combinators ... maybe there is already an existing typeclass that could be leveraged. At least monoid should help out for some parser-combinators of those type of streams. I'm closing this now for obvious reasons...
