### ISSUE TITLE
Clarify the result of updatePos

### ISSUE THREAD

**Issue by feuerbach** [mrkkrp/megaparsec#189]
The documentation for `updatePos` says:

>The result is a tuple where the first element will be used to report parse errors for current token, while the second element is the incremented position that will be stored in parser's state.

From this I understand the purpose of the first element (reporting parse errors for the current token), but not the second one. Ok, it is stored in parser's state, but what is it used for?

**Comment by mrkkrp** [comment]
Yes, this needs clarification. The stored (incremented) position is used whenever position can't be/shouldn't be updated by consuming a token. For example, if you use `failure` we don't grab a new token, we need to fail right were we are now, so error position will be taken from parser's state. Another example is `notFollowedBy`: since it does not modify parser's state/consumes input, it has to use the stored position.

**Comment by feuerbach** [comment]
These two cases look different to me.

In case of failure, shouldn't we use the position of the last token we've seen? Why should it be incremented?

In case of notFollowedBy, it seems like we really need to use the position of the next token (which we must grab anyway in order to know that the next token is erroneous) — why not just use that one?

**Comment by feuerbach** [comment]
I think there may be a misunderstanding here because a "token position" may mean to the start or the end of the token. Here, I am referring to the start position of the token.

**Comment by mrkkrp** [comment]
I think an example might help:

```
def name ()
    ^   ^
    α   β
```

Here let's say we have a token with `name` inside. It has attached info with α as starting position and β as position where it ends. Next token is let's say this `()` thing. When right after we parsed `name` we use `failure` what position should be reported?

* How it works now: position where `name` ends is reported (β).

* You propose to use position of “last token we have seen”. I understand this as if you would report position α which would point to `name`, which we have already parsed without issues.

----

With `notFollowedBy` it may be harder to understand why the current behavior is correct. Yes, we need to grab next token to understand whether it fails or succeeds, but the point of this combinator is that it never advances parser's position, including the case when it fails. It's sort of instant check, not normal consuming parser. So if it fails, it should not increment position, because it fails (like `failure`) right where we are. Why would it report position of next token when we **didn't actually get there**? Yes, in a sense the semantics are a bit arbitrary.

**Comment by feuerbach** [comment]
> I understand this as if you would report position α which would point to name, which we have already parsed without issues.

Yes, this is exactly what I meant. Indeed we "parsed" (recognized) that token without issues. But now for some reason we decide to fail. Why could it be? Since `name` was the last token we have seen, it makes sense to blame it. As in: we've read a token, then decided it was not what we expected, so we failed.

The semantics you describe blames what follows *after* the token. But we haven't even looked there, so how can an error possibly be there?

> the point of this combinator is that it never advances parser's position, including the case when it fails

Sure — but that definition has nothing to do with the error messages. It is simply a statement about what the parser state is going to be when the function returns. In your example, if `name` must not be followed by `()`, the error occurs exactly when we see `()` in the input stream, and no earlier.

**Comment by mrkkrp** [comment]
> Yes, this is exactly what I meant. Indeed we "parsed" (recognized) that token without issues. But now for some reason we decide to fail. Why could it be? Since name was the last token we have seen, it makes sense to blame it. As in: we've read a token, then decided it was not what we expected, so we failed.

> The semantics you describe blames what follows after the token. But we haven't even looked there, so how can an error possibly be there?

I'm afraid we can't make any assumptions why `failure` was used at all. We can't assume that the last token was “not what we expected” (why it even parsed then?). The reason `failure` was used may have nothing to do with the last token, maybe column position now is odd and we expected even position (quite improbable use case, but it should demonstrate the point).

> Sure — but that definition has nothing to do with the error messages. It is simply a statement about what the parser state is going to be when the function returns. In your example, if name must not be followed by (), the error occurs exactly when we see () in the input stream, and no earlier.

I see nothing wrong with this logic. As I said the current behavior is a bit arbitrary.
