### ISSUE TITLE
Use srcloc

### ISSUE THREAD

**Issue by feuerbach** [mrkkrp/megaparsec#190]
Would it be possible to use the types from https://hackage.haskell.org/package/srcloc instead of defining your own? That would increase interoperability between different libraries — for instance, between megaparsec and lexer-applicative.

**Comment by mrkkrp** [comment]
I think it would be a breaking change. We only can consider this for version 6.0.0.

**Comment by recursion-ninja** [comment]
This seems like a very light and useful dependency.

**Comment by ChShersh** [comment]
Probably some new fresh alternative [`loc`](https://hackage.haskell.org/package/loc) library can be used instead of `srcloc`.

**Comment by mrkkrp** [comment]
I decided to go with our custom position module instead.

* `loc` cannot be used because it requires `base == 4.9.*`, we can't drop support for older `base`s. Also, positions are represented as `newtype`s around `Natural`s, which is not what I'd like given our focus on performance is version 6, I'd rather prefer `Int` or `Word`.

* `srcloc` is nicer and does not have those problems, but we do things a bit differently in Megaparsec. Since it's possible to have a stack of source positions, we can't really store token offset in every such position (`SourcePos` or `Pos` in `srcloc`), we need to store it separately in parser's state (and it's not really token offset but the number of processed tokens so far, there is a subtle difference). Of course we could store and update token offsets still, but it does not add anything useful as we already have `stateTokensProcessed`. I also think it's good to keep our `Pos` wrapper for positive integers (we use that for line numbers, column numbers, indentation levels, etc.).

Another consideration is that I'm trying to avoid too drastic changes unless absolutely necessary, so it's easier for people to migrate from version 5 to 6 rather mechanically. Hope you understand my decision.
