### ISSUE TITLE
How to set the error location?

### ISSUE THREAD

**Issue by feuerbach** [mrkkrp/megaparsec#191]
Somewhat related to the discussion in #189, here is what I am struggling with.

I need to parse a n-tuple of the form `(a, b, c)`, except a one-tuple `(a)` should lead to a parse error.
The reported position for that error should be at the left parenthesis token.

How do I do this with megaparsec?

**Comment by mrkkrp** [comment]
First of all, it's quite doable and I'll explain how in a moment. But also perhaps it should be much easier.

----

So how to do it. Two options:

* Use `failure` or `empty` or `fail` (depending on level of parse error fancyness you want) to check for 1-tuple after they are parsed and fail when necessary. Put the entire thing into `lookAhead` — this will give you error messages with position at the beginning of the whole thing. But since `lookAhead` doesn't advance position, you'll need to parse the whole thing once again after `lookAhead` succeeds. I used this in one of my parsers when I wanted something like this. I'm not a big fan of it and I already thought of somethnig to help users to this sort of thing without re-parsing.

* Remember position before you start parsing and use `observing` as explained here: https://mrkkrp.github.io/posts/latest-additions-to-megaparsec.html#the-observing-primitive to replace error position in error if it happens. This should be much easier when we have `region` described in #187. I'm not against providing something out-of-the-box on top on `region` specially for this use case.

(Parsec users somehow lived without all the fancy stuff for years!)

**Comment by mrkkrp** [comment]
Actually I wonder we you could just remember the position and then set it before using `failure`. This will do the trick without re-pasing.

**Comment by feuerbach** [comment]
Regarding your last suggestion, I don't think it's going to work precisely for the reasons discussed in #189. Before `(` is parsed, the parser state will point past the last token but not necessarily at `(`.

**Comment by mrkkrp** [comment]
So you parse stream of tokens from an external tokenizer?

**Comment by feuerbach** [comment]
Yes, I use lexer-applicative.

**Comment by mrkkrp** [comment]
OK, this makes it a bit more hairy. Try this:

1. Get current position.
2. Increment it by manually applying `updatePos` and giving whatever represents `"("`.
3. Now you should have the correct position, so you can set it before signaling error.

This use-case should really be covered out-of-the-box, it shouldn't be that difficult to do this.

**Comment by mrkkrp** [comment]
Tagging this as a feature request. I'll add a helper for this in 5.3.0.

**Comment by feuerbach** [comment]
I don't think `updatePos` is going to work either — the problem is not in `(` itself but in the whitespace that may precede it. But don't worry about it — I know how to hack around it.

I created this issue mainly to find if there was an idiomatic way to do it — so I'd appreciate it if you could add a feature for this.

**Comment by mrkkrp** [comment]
I'm about to start working on this feature, I plan to call it something like `anchor`. Why do you think whitespace is a problem here? I'd thought that it's easy to consume all whitespace before this "anchored block" begins. My idea is that there will be

```haskell
anchor :: MonadPasec e s m => m a -> m a
```

So if a parse error happens inside this, we reset position to beginning of first token that was found before parsing of m in `anchor m` started.

What do you think?

**Comment by mrkkrp** [comment]
GitHub has linked to my PR #199 which implements the feature, if you could take a look and tell me if it's usable in your case, it would be much appreciated.

**Comment by feuerbach** [comment]
Mark,

I'm afraid this is too crude a solution. It re-positions all errors that happen inside the block. If you consider my original example, there may be syntactic issues in the individual elements of the tuple — and I want to report them where they happen. I only want to shift one particular error.

So in terms of the API, I'd prefer something like you described in https://github.com/mrkkrp/megaparsec/issues/191#issuecomment-281410888. 

Re whitespace — I probably didn't understand your suggestion when I wrote https://github.com/mrkkrp/megaparsec/issues/191#issuecomment-281419653. I've now looked at the code of `anchor` and it seems to do the right thing. Now if you could package that as two separate functions:

1. get the "current" position (the position of the next token — which is different from the position recorded in the parser state), and
2. apply that position to a parser (where the parser in my case would be just `fail msg`)

then this would be great.

**Comment by mrkkrp** [comment]
I see, thanks for your feedback. I'll add a helper to get current position, it should be already possible to set it with `setPosition` just before you `fail`.

**Comment by mrkkrp** [comment]
I added `getNextTokenPosition` in #202.
