### ISSUE TITLE
Support lexical errors

### ISSUE THREAD

**Issue by feuerbach** [mrkkrp/megaparsec#196]
The signature of `uncons` is:

```
uncons :: s -> Maybe (Token s, s)
```

It means that either a token is available (`Just`), or we have reached EOF (`Nothing`). However, there is a third possibility: while trying to produce the next token, a lexical error has occurred.

It would be nice to support this case and be able to turn a lexer error into a megaparsec error.

**Comment by mrkkrp** [comment]
I thought about this and I think that it would introduce so much complexity that it would outweigh that relatively little benefit the feature may provide. If we step on this path, we'll need to adjust every method of `Stream` because things like `takeWhile_` also can get into a lexical error at any point.

I think it's better to assume that lexer has done its work and we have a stream of valid tokens for parsing and all lexical errors have been reported by lexer itself by the time we start parsing. Don't get me wrong, this is a nice feature, but it comes at a cost, so I'm trying to balance the feature set and complexity here.

I intend to close this if you don't mind.

**Comment by feuerbach** [comment]
Sure, I'm fine with it.
