### ISSUE TITLE
Meaning of "unknown parser error"

### ISSUE THREAD

**Issue by themoritz** [mrkkrp/megaparsec#201]
I sometimes get this when working on my parser, and can't even pin down which changes lead to the message. So what's the meaning of "unknown parser error"? Also helpful would be an example of a parser that leads to this error.

**Comment by mrkkrp** [comment]
"Unknown parser error" is how `ParseError` without any expected/unexpected tokens or custom data is rendered. Normally it does not happen often. If you show me piece of your code that produces the error, I can help you understand why you're getting it.

May I suggest using of `dbg` to track down where/why it happens?

**Comment by themoritz** [comment]
Thanks for the quick reply and offering to look at the code! I managed to solve the issue, and the problem was that I forgot the `try` in the following parser:

```haskell
identifier :: Parser Text
identifier = try go <?> "identifier" where
  go = do
    s <- name
    guard (s `notElem` reservedNames)
    pure s
```

I only did backtracking in the `name` parser, but after it succeeded the guard could still cause the `identifier` parser to fail.

The whole parser is quite involved, and I still cannot reproduce the error in a small example, which would be nice to completely understand in what situations one gets the "unknown parse error".

**Comment by mrkkrp** [comment]
You should try to avoid `guard`, because if its argument evaluates to `False`, it's the same as `empty`, which has no info associated with (due to its "abstractness"), so that's why you're getting "unknown parser error". A better approach would be to use `fail` with an explicit message:

```haskell
identifier :: Parser Text
identifier = try go <?> "identifier" where
  go = do
    s <- name
    if s `elem` reservedNames
      then fail "A reserved name cannot be used as an identifier."
      else return s
```

You can do even better if you want, by having well-typed custom error component, so you could describe your error not as a `String`, but as a value of some sum type, etc. To learn how to do that, see this tutorial:

https://mrkkrp.github.io/megaparsec/tutorials/custom-error-messages.html

**Comment by themoritz** [comment]
That makes a lot of sense, thanks!
