### ISSUE TITLE
Flip argument order for “label”

### ISSUE THREAD

**Issue by neongreen** [mrkkrp/megaparsec#21]
It'd be nice if it was possible to use `label` like this:

~~~ haskell
yearP :: Parser Integer
yearP = label "year" $ do
  s <- some digit
  return $ if length s < 4 then 2000 + read s else read s
~~~

(The current signature is `label :: ParsecT s u m a -> String -> ParsecT s u m a`.)

**Comment by tulcod** [comment]
[minor issue]
In that case, that would be a good opportunity to rename it, to avoid confusion with parsec's label. Additionally, is "label" the name that makes the biggest amount of sense for this function? Since it's more of an error report... "label" suggests that you always see this information, whereas it really is a bit of feedback that you only receive in the "negative" case... Maybe "feedback" or "reporting":
```haskell
yearP :: Parser Integer
yearP = reporting "year" $ do
  s <- some digit
  return $ if length s < 4 then 2000 + read s else read s
```
read as "reporting {error message} [in case of failure, rather than the default message somewhere deep down in this parser], do ..."
Just my $0.02 though, "label" is perfectly acceptable, and I am probably bikeshedding here.
[/minor issue]

**Comment by neongreen** [comment]
> that would be a good opportunity to rename it, to avoid confusion with parsec's label

Well, this depends on just how much @mrkkrp values compatibility with Parsec. (Even if “not much”, given how small this issue is, the exact amount of “not much” starts to matter here.) Another thing to keep in mind is that *(I think)* `label` isn't used often and thus changing its type won't cause practically any harm.

> Since it's more of an error report...

Hm. At least in my mental model, it's not “an error report”, but “how is this parser called” (a datapoint: before I looked at the docs, I was pretty sure it was called `name` and not `label`). Yeah, parser names are only used in error reports, but I still think of them as of *names* internally. `reporting` sounds more like “in case of parsing failure, report this error: ...”.

**Comment by mrkkrp** [comment]
@neongreen, I actually had this on my mind when I wanted to write `hidden = label ""`. I think it's indeed may make writing of some long parsers easier, I see your point. I'll commit necessary changes soon.

@tulcod, I don't value compatibility with Parsec in this project. After all, it already has many functions that are called differently and even a couple of them that have the same names but do different things (yes `count`, I'm looking at you). However, I just think that `label` is simple and intuitive name for this combinator.

It's obvious even from this little discussion that different people have different associations and would like to call it differently (`name`, `reporting`). I think there is no real reason for renaming, let it be `label`, after all `<?>` form is used more often afaik.
