### ISSUE TITLE
Selectively ignoring parts of a file?

### ISSUE THREAD

**Issue by daniel-beard** [mrkkrp/megaparsec#212]
Hi, thanks for the awesome library! I'm relatively new to Haskell dev. I'm having an issue trying to "selectively" parse a file: E.g.

I have a file with lots of function declarations as well as other things. All I'm really interested in is parsing the functions. Does megaparsec expose something to help with this (ignoring everything other than what I want to parse)?

E.g.

```
class MyClass {

    // some comments
   Possibly some bad syntax here.

   func thisIsAFunction() {
      print("Hello World");
   }

   func anotherFunction() { }
}
```

**Comment by mrkkrp** [comment]
You need to skip parts of input between the definitions. Let's say you have `pFunc` parser that parses things like `func functionName () { … }`. Then in simplest case you could use something like `skipTillNextFunc`:

```haskell
skipTillNextFunc :: Parser ()
skipTillNextFunc = void $ manyTill anyChar (lookAhead pFunc <|> eof)
```

This will skip everythnig till `pFunc` succeeds (meaning that we have located a valid occurrence of function), or we have reached the end of input. The function's definition itself is not consumed though, because of the `lookAhead` wrapper.

Then the whole parser could be something of this sort:

```haskell
parseManyDefinitions :: [Denifition]
parseManyDefinitions = between skipTillNextFunc eof $
  many (pFunc <* skipTillNextFunc)
```

We need to run `skipTillNextFunc` first to skip to the first function in the input.

This should give you an idea how to tackle it.

**Comment by daniel-beard** [comment]
This looks to be exactly what I need. Thanks for the help and the awesome library!
