### ISSUE TITLE
Stackage version is not the latest

### ISSUE THREAD

**Issue by jaseemabid** [mrkkrp/megaparsec#240]
I see v6.0.2 released here, but only 5.2.0 on stackage lts-8.24 and it's not even available on the current latest stackage, lt-9.0

What is the recommended approach to using latest version of both together? 

https://www.stackage.org/lts-8.24/package/megaparsec-5.2.0

**Comment by recursion-ninja** [comment]
You can put this in your `stack.yaml` file until the new version of `megaparsec` is picked up in a later LTS snapshot:

    extra-deps:                                                                                                                                 
      - megaparsec-6.0.2

**Comment by jaseemabid** [comment]
Should I leave the bug report open till the latest version of megaparsec is available on some version of stackage?

**Comment by mrkkrp** [comment]
Well, I think there is nothing we can do *with the library itself* to resolve this, so it does not belong here. There is an issue on Stackage issue tracker for this: fpco/stackage#2666.

Since there are projects that depend on Megaparsec and version 6 is a major release that can break things, it takes some time for people to upgrade. Eventually version 6 will be on Stackage.
