### ISSUE TITLE
Default implementation for the ShowToken class?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [mrkkrp/megaparsec#270]
Seems like I'm missing a ShowToken instance for the tokens I'm parsing over.

Looking at the code, it seems like there should be a default:

```

class Show a => ShowToken a where

  -- | Pretty-print given token. This is used to get token representation
  -- for use in error messages.

  showToken :: a -> String
  default showToken = show
```

or something like that?

**Comment by mrkkrp** [comment]
I don't think this is a good idea because:

* The there is no reason to require `Show` be a superclass of `ShowToken`.
* Please note that your signature of `showToken` is incorrect. There is no such method as `showToken` at all, we have `showTokens` instead because we don't want to handle single concrete characters and multiple concrete characters in error messages differently. This way single character `'a'` and a string with a single character `"a"` cannot be different, which is important.
* `show` is never a good default for this method. `show` produces programmer-oriented representation, while `showToken` must produce user-friendly representation. For example if I have some Unicode in a string or character, then `show` will render it as `"\123blah"`, while in `showToken` I want actual Unicode to be rendered. This is just one example. I think we do the right thing right now forcing users to give a good implementation instead of silently defaulting to something unexpected.

Also, you don't need the `default` keyword here, it serves a different purpose, see:

https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#default-method-signatures

**Comment by mrkkrp** [comment]
Unless there is something else to be considered, I close the issue.

**Comment by alexanderkjeldaas** [comment]
My use-case is to parse internal data structures.  The parser is "guaranteed" to succeed, or else it's because the parser functions are not total, which then is GHCs problem to solve.

So the idea that the messages are for users is wrong.  There is no user, so the requirement to write something helpful to the non-user is just busywork.

Thus some default implementation would help and make this useful.

What's the use-case for parsing non-Text, non-String data where there is a "user" and not a programmer that should consume the errors?

**Comment by mrkkrp** [comment]
> So the idea that the messages are for users is wrong.

Well it can't be *right* or *wrong*. There is a common need to be able to present parse errors in human-readable form, and the functions like `parseErrorPretty` do just that. If you don't need to present your parse errors in human-readable form, then you don't need to define `ShowToken` instances at all!

I think your use case is rather special and as such it's not a reason to introduce default implementations that may be helpful for you, but may as well lead to unexpected results for others.

> What's the use-case for parsing non-Text, non-String data where there is a "user" and not a programmer that should consume the errors?

You could parse a stream of some tokens and still want to present parse errors in human-readable form, why not?
