### ISSUE TITLE
Can you add descriptive example for newbies?

### ISSUE THREAD

**Issue by a-x-** [mrkkrp/megaparsec#272]
```hs
a   ::= x | n | - a | a opa a
b   ::= true | false | not b | b opb b | a opr a
opa ::= + | - | * | /
opb ::= and | or
opr ::= > | <
```

**Comment by a-x-** [comment]
taken from https://markkarpov.com/megaparsec/parsing-simple-imperative-language.html

**Comment by mrkkrp** [comment]
Well it's already in a tutorial and we link to tutorials from many places. I see that you had no problem discovering the example. I think we should not turn Haddocks into tutorials, the two kinds of documentation (tutorials and Haddocks) are different and complementing, and should not be arbitrarily mixed.

Maybe if you describe in more detail your motivation and thoughts on the matter we could find how to improve the documentation.

**Comment by a-x-** [comment]
Thank you, I do like separating doc kinds and do it myself too in many cases.

But I think that it will be more clear, if example will be on the readme.

Also, link to tutorial is not such visible and it's may be hard to find it out.

In my case I wanted to quick compare a few libraries.

**Comment by mrkkrp** [comment]
Well, the readme has a link to tutorials and there is an item "Tutorials" in the table of contents. And also there is a link to tutorials right here:

https://hackage.haskell.org/package/megaparsec-6.4.0/docs/Text-Megaparsec.html

> But I think that it will be more clear, if example will be on the readme.

So in the readme or in the Haddocs? In any case, even if we add a simple example to the readme, it won't be helpful for library comparison because it'll just scratch the surface. The readme in its current form describes a lot of details that are more useful for comparing libraries. I'll close this, if you don't mind.
