### ISSUE TITLE
Missing module documentation for Text.Megaparsec.Perm

### ISSUE THREAD

**Issue by alexanderkjeldaas** [mrkkrp/megaparsec#276]
The current documentation is:

```
This module implements permutation parsers. The algorithm is described in:
 Parsing Permutation Phrases, by Arthur Baars, Andres Loh and Doaitse Swierstra.
 Published as a functional pearl at the Haskell Workshop 2001.
```

This doesn't describe what a permutation parser is.

**Comment by recursion-ninja** [comment]
It is described in the abstract & introduction to the [referenced paper](https://pdfs.semanticscholar.org/93fc/3597a70bbc03107e833126913b0c8ce999f1.pdf):

>  A permutation phrase is a sequence of elements (possibly of different types) in which each element occurs exactly once and the order is irrelevant. Some of the permutable elements may be optional.

Perhaps that should be added into the module description?

**Comment by recursion-ninja** [comment]
I would suggest preferring the `Control.Applicative.Permutations` module from the `parser-combinators` package that `megaparsec` depends on over the `megaparsec` package's own `Text.Megaparsec.Perm` module.

It doesn't appear to me that the `Text.Megaparsec.Perm` module provides less functionality than the  `Control.Applicative.Permutations` module. I wonder if this module should be deprecated. That's a question for @mrkkrp .

**Comment by mrkkrp** [comment]
That's a good question. We could actually deprecate and remove it in version 7. It so happened that I have not used permutation parser myself, so I'll need to compare the two modules and decide whether we can drop `Text.Megaparsec.Perm`. @recursion-ninja, your opinion?

**Comment by recursion-ninja** [comment]
I believe that `Control.Applicative.Permutations` can replace `Text.Megaparsec.Perm`, but it would be prudent to have a test suite and possibly benchmarks that we can run against both implementations to ensure that there is no loss of functionality or a performance regression. What is the timetable for version 7? Is there enough time to incorporate that before the version 7 release?

**Comment by mrkkrp** [comment]
Yeah, sure we'll have tests+bechmarks for `Control.Applicative.Permutations` in that case. Version 7... maybe summer 2018. No hurry.

**Comment by mrkkrp** [comment]
@recursion-ninja I'm working on dropping `Text.Megaparsec.Perm` and so I'm writing tests for `Control.Applicative.Permutations`. Here is what bothers me:

https://github.com/mrkkrp/megaparsec/blob/drop-permutations/tests/Control/Applicative/PermutationsSpec.hs#L66

You see, with the parser:

```haskell
      let p = f <$> toPermutationWithDefault 'x' (char 'a')
                <*> toPermutationWithDefault 'y' (char 'b')
                <*> toPermutationWithDefault 'z' (char 'c')
          f a b c = a:b:c:[]
```

Input `"bbc"` results in output `"xbz"`, while I'd expect `"xbc"` here. Can you comment on this? Maybe it's a feature of the algorithm? My logic is:

* There is no `'a'`, so the first character must be `'x'` (correct).
* There is a `'b'`, so the second character must be `'b'` (correct).
* There is a `'c'`, so the third character must be `'c'`, but we get `'z'` here (incorrect).

I also left another comment here: https://github.com/mrkkrp/parser-combinators/commit/a91ea09b0490347815cd3e87a75ddea70353686c#r28734910.

**Comment by recursion-ninja** [comment]
@mrkkrp At a cursory glance, the example you provided looks like there may be a defect in the parser. I'll investigate the matter this weekend. I had an idea for optimizing the implementation so I'll tinker with that and ensure that provided example correctly parses correctly.

**Comment by recursion-ninja** [comment]
@mrkkrp I've given it more thought and I'm convinced this is a feature of the permutation parser. It comes down to the assumption that if a parser fails to match an atomic token provided _and_ is specified to default to a known value, nothing is parsed for that defaulted token.

In the example above, here's what's happening mechanically:

 * Scan the first _three_ permutation tokens in the stream `"bbc"` for the token `'a'`. In this case that's `'b'`, `'b'`, & `'c'`.

    * There is no `'a'`, so the first return character must default to `'x'`.
    * The stream is left unchanged.
    * Consequently, because the token `'a'` wasn't found, the parser will parse at most _two_ tokens total.

 * Scan the first _two_ permutation tokens in the stream `"bbc"` for the token `'b'`. In this case that's `'b'` & `'b'`.
    * There is a `'b'`, so the second return character is be `'b'`.
    * Either the first `'b'` token or the second 'b' token will be removed from the stream depending of the parse result of the last token.
    * Since the token parser succeeded, the parser will still parse at most _two_ tokens total.

* Scan the first _two_ permutation tokens in the stream `"bbc"` for the token `'c'`. In this case that's `'b'` & `'b'`.
    * There is no `'c'`, so the third return character defaults to `'z'`.
    * The first `'b'` token will be parsed because the previous 'b' token succeeded and there was no `'c'` token.
    * Consequently, because the token 'c' wasn't found, the parser will parse one token (`'b'`), and the stream will remain as `"bc"`.

This functionality is quite desirable for parsing "function arguments" with defaults. Consider this example:

       let functionDef = show
           functionArgs = (,,) <$> toPermutationWithDefault 42 (integer <* space)
                               <*> toPermutationWithDefault 1.0 (decimal <* space)
                               <*> toPermutationWithDefault False ( ((string' "True" *> True) <|> (string' "False" *> False)) <* space)
       in (string' "functionName *> space *> functionDef) <*> functionArgs

The input `"functionName"` results in output `"(42, 1.0, False)"` because all inputs defaulted.

The input `"functionName True 1 False"` results in output `"(1, 1.0, True)"` because the only the "real-valued" 2nd argument is defaulted and consequently the later `"False"` is ignored and left in the stream.

The input strings for the function definitions can look more C like by using `intercalateEffect` to intercalate `(space *> char ',' <* space)` tokens between the arguments with default options. Inputs can then look like `"functionName ( arg1, arg2  , arg3  )"` with `arg1`, `arg2`, and `arg3` occurring in any order and possibly being defaulted.

Does my logic make sense? I hope I explained the functionality/theory well enough. I believe that is functionality is similar to the other permutation parser libraries/implementations, though it's been a while since I've surveyed them and my recollection might be wrong.
