### ISSUE TITLE
How to indentGuard with greater or equal to?

### ISSUE THREAD

**Issue by arch-mage** [mrkkrp/megaparsec#277]
I need to make the parser to be valid for

    token
    token

and this

    token
     token 

Basically, the indentation must be greater or equal to the header. My first solution is to decrement
the reference indentation like this:

    ref  <- indentLevel
    tok1 <- token
    tok2 <- indentGuard scn GT (ref -1) *> token

But the `ref` which is a `Pos` is not an instance of `Num`, so I can't make it works. And there is no
`GTE` for `Ordering`. If only `Pos` is an instance of `Num` it will be easier.

Is there any solution?

**Comment by mrkkrp** [comment]
You could do the following:

```haskell
module Main (main) where

import Control.Monad
import Data.Void
import Text.Megaparsec
import Text.Megaparsec.Char
import qualified Text.Megaparsec.Char.Lexer as L

type Parser = Parsec Void String

myToken :: Parser String
myToken = string "token"

scn :: Parser ()
scn = space

myParser :: Parser (String, String)
myParser = do
  ref  <- L.indentLevel
  tok1 <- myToken
  -- tok2 <- (try (L.indentGuard scn EQ ref) <|> L.indentGuard scn GT ref) *> myToken
  -- alternatively, faster:
  tok2 <- do
    scn
    void $ L.indentGuard (return ()) EQ ref <|> L.indentGuard (return ()) GT ref
    myToken
  return (tok1, tok2)

main :: IO ()
main = do
  let input1 = "token\ntoken\n"
      input2 = "token\n token\n"
      input3 = " token\ntoken\n"
  parseTest' myParser input1
  parseTest' myParser input2
  parseTest' (scn *> myParser) input3
```

Outputs:

```
λ> :main
("token","token")
("token","token")
2:1:
  |
2 | token
  | ^
incorrect indentation (got 1, should be equal to 2)
incorrect indentation (got 1, should be greater than 2)
```

Well sure, the error message could be better, but it's still accurate.

----

`Pos` is a thing that represents indentation levels and tab widths, as such it's a very special sort of number. It can be only positive, so it's not a very meaningful instance of `Num`. Although it's a good and very efficient `Semigrop` which is quite enough for our purposes :-)

**Comment by arch-mage** [comment]
Okay, I get it. But, nested `indentGuard` seems ugly I think. It'll be nice if there's an alternative for `indentGuard` which takes a predicate instead of ordering. Just an idea tough.

Thanks anyway :smile:

**Comment by mrkkrp** [comment]
Well it's not really nested, we just have an alternative here, which is a very common thing. I don't see anything ugly about this. I agree that the error message could be better, however.

Well, I think you'll agree that taking a predicate is the first thing that comes to mind. So why it's done this way instead? It's because a predicate, being just a function, is not *inspectable*, so it cannot help much with generation of good error messages that could explain user what is expected. We'd need to take a predicate together with something that would describe what it does, and that is certainly ugly and error-prone too (because now you have two different things that essentially convey the same information). So the actual solution you see is *good enough* I think.
