### ISSUE TITLE
Name clashes with Control.Applicative

### ISSUE THREAD

**Issue by recursion-ninja** [mrkkrp/megaparsec#286]
Library users can no longer import both `Control.Applicative` and `Text.Megaparsec` because `megaparsec` exports different `many` and `some` combinators with the `MondaPlus` constraint. Because of this I cannot use `megaparsec` as a Free Applicative interpreter without littering all my imports with `hiding` statements or qualified imports..

Consider re-exporting the canonical implementations from `Control.Applicative`. Compatibility with the Haskell core libraries and the rest of the Haskell ecosystem is one of `megaparsec`'s strengths. We shouldn't just throw that away.

**Comment by mrkkrp** [comment]
> Comparability with the Haskell core libraries is one of megaparsec's strengths.

It is, but the default `many` and `some` are too inefficient and leaky. Use `hiding` in import sections, either hide Megaparsec's `many` and `some` or `Control.Applicative`'s `many` and `some` (better).

The difference in performance is significant, I did not make this change as a whim.

See for example max residency numbers here:

https://github.com/mmark-md/mmark#performance

It's 37,792 vs 799,200 of cheapskate (closest Haskell competitor). This affects speed of execution also. This is just too important performance-wise to ignore and blindly prefer `many` and `some` from `Control.Applicative` just because they come from `base`. From software engineering perspective that switch is a good thing, and it does not make Megaparsec less compatible with `base`, just requires hiding a couple of functions, which is a non-issue compared to the benefits.

**Comment by recursion-ninja** [comment]
I appreciate the concern for performance, but I now need to update several dozen parsing modules across our codebase. I would have expected this to be "opt-in" by importing `Control.Monad.Combinators` explicitly, rather than it being implicitly imported for me. I think that if `Text.Megaparsec` is going to export `some` & `many` functions, they should be re-exported from `Control.Applicative`.

**Comment by mrkkrp** [comment]
What is better:

* You got into position where you see an explicit name clash, you're fully aware what that means and you can thus decide what is best for you. The change is mechanical and can be performed (semi-)automatically with e.g. Emacs. Even if you have dozens of modules it's not more than 10 minutes.

* Megaparsec's users are by default given an inferior option and they will be most likely unaware of better versions of `many` and `some` for quite some time.

My position is that we should export the best tools by default, and it would be strange to replace most combinators by their monadic optimized versions with exception for very common `many` and `some`, just because of a minor inconvenience with importing.

**Comment by mrkkrp** [comment]
> There's also the question of if the single markdown file for the benchmark is a representative sample of all parser use cases. The benchmark also didn't provide megaparsec's performance with Control.Applicative.Combinators vs Control.Monad.Combinators.

That's just a vivid example to show off, so I quote it. I carefully compared performance of applicative and monadic combinators using not only mmark benchmarks (it has more benchmarks, the one quoted is an external experiment in another repo) but also megaparsec's own benchmarks and how this switch affects [these benchmarks](https://github.com/mrkkrp/parsers-bench). In addition to that there are [Stache](https://github.com/stackbuilders/stache) benchmarks as well. I trust that if all these show improvement, then there is an improvement.

There were also discussions and experiments between me and other interested people (not public) that showed very clearly that it's a win even before I started working on the switch.

**Comment by recursion-ninja** [comment]
Sounds very well thought out and tested. In light of that information, I'm going to back peddle on my position. I'll update our codebase to use the `Control.Monad.Combinators` where applicable and I'm looking forward to some speed ups. If there are performance regressions, I'll be sure to let you know.

One last suggestion, in the  "Re-exports" section of `Text.Megaparsec` module's header documentation, a note about `Control.Monad.Combinators` being re-exported with "overly constrained" functions is to provide better performing versions of the `base` functions would be very informative to users like me.
