### ISSUE TITLE
Parser that succeeds when a given parser fails

### ISSUE THREAD

**Issue by ghallak** [mrkkrp/megaparsec#309]
Is there a parser that succeeds when a given parser fails?

For example, when I need a parser that succeeds for any character other than the end of line `\n` or `\n\r`, I do the following:

```haskell
nonEolCharP :: Parser Char
nonEolCharP = satisfy (\c -> c /= '\n' && c /= '\r')
```

What would be nice is a parser (`notP`), so that I can use [`eol`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char.html#v:eol) to do the following:

```haskell
nonEolCharP :: Parser Char
nonEolCharP = notP eol
```

**Comment by mrkkrp** [comment]
The problem here (for general case, `notP :: MonadParsec e s m => m a -> m a`) is that once the argument parser fails we have no way to actually understand what to match. Should we match the part of input stream that the failing parser consumed before it failed? Probably not, and certainly not if it was used with `try` which backtracks stream consumption info.

In general, if you have `pA :: Parser A` and then you want `notA = notP pA`, then how once `pA` fails you can figure out what to fetch from input stream and most importantly how to turn that into `A` to return in the end?

That said, you could take a look at `notFollowedBy`, it's often useful, although in slightly different circumstances.

**Comment by mrkkrp** [comment]
I guess we can close?

**Comment by ghallak** [comment]
>The problem here (for general case, notP :: MonadParsec e s m => m a -> m a) is that once the argument parser fails we have no way to actually understand what to match.

You're right, I haven't thought about that. `notFollowedBy` seems to do what I want.

Thanks
