### ISSUE TITLE
Can I map over the error type of a ParsecT?

### ISSUE THREAD

**Issue by TikhonJelvis** [mrkkrp/megaparsec#339]
I have some existing parser code that I'm changing to support a custom error type (`VersionError`).

Changing my own code has been straightforward, but I also depend on a parser imported from another package that has a `Void` error type:

```
λ> semver'
semver' :: Parsec Void Text Data.Versions.SemVer
```

Can I change `semver'` to a `Parsec VersionError Text Data.Versions.SemVer`? I found `mapParseError`, but I'm not sure how to turn it into something like this:

```
mapError :: (Ord e') => (e -> e') -> ParsecT e s m a -> ParsecT e' s m a
```

**Comment by mrkkrp** [comment]
Sorry for the delay with my response. I still don't have internet connection in my apartment here in Paris, so I mostly do everything programming-related in the office.

To answer your question, in `semver'` `Void` should be probably replaced by `a` so it works with any type of custom error component. If you don't have control over source code of `semver'` then perhaps you could coerce one into another (because `Void` is for sure never produced there, it should be OK). I'm pretty sure we don't have anything for the conversion out-of-the-box right now.

**Comment by mrkkrp** [comment]
I imagine you could use the internal module, unwrap `ParsecT` and then re-wrap the lambda to change the types.

**Comment by TikhonJelvis** [comment]
No worries. Hope you're enjoying Paris :).

Do you think it would make sense to add a function to do this to megaparsec? I don't know how common my particular usecase is.

**Comment by TikhonJelvis** [comment]
If it does make sense, I'm happy to take a stab at a PR.

**Comment by mrkkrp** [comment]
> Do you think it would make sense to add a function to do this to megaparsec?

Do don't see why not.

**Comment by mrkkrp** [comment]
I'm gonna close this one. You are welcome to open a PR, although afaiu the mapping function would end up in internal module anyway because it'll work only on `ParsecT` things and not on any instance of `MonadParsec` (for that it should be added as a method to the type class, which is no-go).
