### ISSUE TITLE
Should string' return the actual parsed string?

### ISSUE THREAD

**Issue by neongreen** [mrkkrp/megaparsec#36]
Currently it returns its argument, unlike `char'`. It seems to me that returning the parsed string could be more useful, especially if it can be made faster than naive `string' = mapM char'`.

**Comment by mrkkrp** [comment]
Unlike `char'` you probably are not interested in raw result but rather in its “normalized” form. Imagine you're parsing case-insensitive language. I think you would like to have all keywords to be uniformly cased (lowercased or upcased). Well, that's what I would want.

It's easy to make it return actually parserd string though, see `pTokens`. Perhaps that's what we should do, because I tried to preserve original information where possible (for example `eol` returns `\n` or `\r\n` depending on what has been parsed, etc). “Normalization” can be performed on parsed result anyway.
