### ISSUE TITLE
How to migrate 6.X Stream code to 7.X ?

### ISSUE THREAD

**Issue by symbiont-arnaud-bailly** [mrkkrp/megaparsec#391]
I am  trying to port code for https://github.com/qfpl/hpython from megaparsec 6.X to 7 and I am running into an issue when trying to migrate a custom `Stream` implementation. 
Specifically, I find it hard to relate the code for `advance1` et al. which looks like:

```
  positionAtN Proxy spos (PyTokens tks) =
    case tks of
      [] -> spos
      _ ->
        let
          ann = pyTokenAnn $ last tks
        in
          SourcePos
            (_srcInfoName ann)
            (Megaparsec.mkPos $ _srcInfoLineStart ann)
            (Megaparsec.mkPos $ _srcInfoColStart ann)
```
to the new signature for `reachOffset` which, according to the documentation, supposedly replaces the previous functions. `reachOffset` takes and offset and a state, but the parser does not have a state or it's not clear what this should be.

Could someone points me into the right direction?

**Comment by mrkkrp** [comment]
Every parser has a state. Full parser state is the `State s e` type, which also contains `PosState`—a special state for position advancement. Note that offset is different from source position. Offset in just how many tokens have been consumed so far, it doesn't have line number or column number inside. So, `reachOffset` does two things at the same time:

* it builds the offending line to show
* it calculates human-readable source position with column and line numbers.

I'm afraid that's all I can tell you so far, because your question is not clear and I do not have time to dig into the project you mention. If you can come up with a more precise question(s), I'll try my best to answer.

**Comment by symbiont-arnaud-bailly** [comment]
Sorry for being unclear. 
I am unfamiliar with megaparsec  and just trying to upgrade a third-party tool we use a recent mp version for dependencies mgmt purpose. I am currently "stuck" converting the  `Stream` instance for the hpython parser here: https://github.com/qfpl/hpython/blob/develop/src/Language/Python/Internal/Parse.hs#L147

Given what's written in mp's Changelog for version [7.0.0](https://hackage.haskell.org/package/megaparsec-7.0.0/changelog):
> Introduced PosState for calculating SourcePos from offsets and getting offending line for displaying on pretty-printing of parse errors. It's now contained in both State and ParseErrorBundle.
> Dropped positionAt1, positionAtN, advance1, and advanceN methods from Stream. They are no longer necessary because reachOffset (and its specialized version reachOffsetNoLine) takes care of SourcePos calculation.

and the current implementation, it's unclear to me what's the path forward as I cannot relate the old `positionAtN` et al. functions which do not have any mention of `PosState`, with the new `reachOffset` function which is all `PosState`  based. 

I guess an example implementation would be helpful, I will look for them in the source tree.

**Comment by symbiont-arnaud-bailly** [comment]
What would help me without you needing to grok hpython's code is an example of parser with a custom `Stream` implementation that's been migrated from version 6.X to version 7.0.0

**Comment by mrkkrp** [comment]
Maybe this could help: https://markkarpov.com/tutorial/megaparsec.html#working-with-custom-input-streams.

**Comment by symbiont-arnaud-bailly** [comment]
Thanks a lot! It does indeed help :)
