### ISSUE TITLE
support Map or Lists with uniq identifier 

### ISSUE THREAD

**Issue by nalchevanidze** [mrkkrp/megaparsec#395]
in most of cases we need to parse fields or some types with uniq identifier. it would be nice if parser could handle this for us.

like that.

```hs 
uniq ::  Eq k => m (k , v) -> m (Map k v) 
```
or

```hs
uniq ::  Eq k => m (k , v) -> m  [(k , v)]
```  
second version gives us flexibility of converting with `fromList` to `Map`, `HashMap` ...etc

**Comment by mrkkrp** [comment]
This looks to me like something too specialized to belong in the library itself. How would you implement this combinator?

**Comment by mrkkrp** [comment]
To expand on what I've said: it is not clear what the semantics should be. How should duplicates be handled (should they result in a special kind of error)? What if you have something like commas between the individual elements (presumably this is what the argument of the type `m (k, v)` means)?

Because of this, so far, I see this combinator as something specific to a particular user situation rather than something that can be reused in many situations.

**Comment by nalchevanidze** [comment]
@mrkkrp  thanks for your response.  as the name is `uniq` it is expected that duplicates should throw error. my idea was that `m (k ,v)` where `k` is a key fail if there is 2 result with same key.

> What if you have something like commas between the individual elements

one possible approach could be this

```hs
uniqKey ::  Eq k => m [(k , v)] -> m [(k, v)] 
uniqKey = .... check uniq keys

manyUniq = uniqKey . many 

commaSepUniq = uniqKey . (`sepBy`  (char ',')) 
```

but i see the problematic of beeng too specific.

**Comment by mrkkrp** [comment]
Even if we just concentrate on the problem of error reporting, it is a tricky one. If we put something like this in the main library, we'd need a special kind of error for this situation like we already have with `ErrorFail` and `ErrorIndentation` [see here](https://hackage.haskell.org/package/megaparsec-8.0.0/docs/Text-Megaparsec-Error.html#t:ErrorFancy). I'm not a big fan of having even those, but they seem to be necessary. Uniqueness checks on the other hand are very application-specific, so they should be defined as custom error messages instead. Since we do not know anything about user-defined custom errors, we cannot use them in the functions that come with Megaparsec.

**Comment by nalchevanidze** [comment]
is it not possible to use current label (e.g `FieldDefinition`)

```hs
fieldDefinition :: Parser (Key, FieldDefinition)
fieldDefinition = label "FieldDefinition" $ do
...

fieldsDefinition = uniqKey $ many fieldDefinition
````
to produce error something like: `FieldDefinition must have uniq keys`

i am not proposing new specific error type for it. 

it is okey if it does not works. we can close this issue. and thank your for your library ,`megaparsec` made my life easier

**Comment by mrkkrp** [comment]
Labeling is used to replace collections of expected tokens, which is something totally different. What you're proposing is unfortunately quite hacky.
