### ISSUE TITLE
Add type-synonym for String parser to Text.Megaparsec.Char

### ISSUE THREAD

**Issue by ibispi** [mrkkrp/megaparsec#418]
Another issue by my friend who doesn't use github:

"Streams of Strings are 95% of what I parse day-to-day. Megaparsec has no type synonym for «Parser that deals with a String input». This means I have to declare it every time myself, importing `Data.Void` and other boilerplate.
Solution: put something similar to `type StringParser = ...` in `Text.Megaparsec.Char`."

**Comment by mrkkrp** [comment]
I think that defining a type synonym for your parser every time is a good practice. It is not hard and results in uniform organization of your parsing code every time. On the other hand if we start defining stock type synonyms we'll need a bunch of them and still we won't cover all use cases because of combinatorial explosion.

Your friend parses `String`s; I parse `Text` and almost never `String`s. Some people parse `ByteString`s. Another component of parser type is the type of custom component of error messages. Your friend perhaps doesn't use this feature, but I do, and many other users do. We could add special type synonyms for some very popular combinations, but it is of very minor value in practice (define your own `Parser` in 10 seconds and be done) and I personally do not like having special-case type synonyms: I have to look them up anyway. Look at `conduit` for example, they had a bunch of type synonyms and what happened eventually? Right, they deprecated them. It is easier to code when you can see the types as they are.

So, all in all, I do not think it is a good idea.
