### ISSUE TITLE
Operator precedence issue

### ISSUE THREAD

**Issue by xhliu** [mrkkrp/megaparsec#445]
I was parsing a C-like language with array and struct. Following C operator precedence, **.** and **[]** are made of equal precedence.
```
opTable :: [[Operator Parser Expr]]
opTable = [[ InfixL $ Access <$ symbol "." , opSubscript]]

opSubscript = Postfix $ foldr1 (.) <$> some singleIndex
singleIndex = do
    index < brackets expr
    return $ \l -> ArrayIndex l index
```
When parsing
```
Struct S {
  int[3] a;
}
Struct S s;
s.a[1]
```
it yielded
`Access (Var "s") (ArrayIndex (Var "a") 1)`
instead of
`ArrayIndex (Access (Var "s") (Var "a")) 1`
Why? Is it because [] is not parsed as InfixL?

Update:
After [changing](https://www.reddit.com/r/haskell/comments/lo29o2/operator_precedence_issue_when_parsing_with/) it to
```
opTable :: [[Operator Parser Expr]]
opTable = [[ PostFix $ (\ident expr -> Access expr ident) <$ symbol "." <*> identifier, opSubscript]]
```
I got another error
```
s.a[1]
|  ^
unexpected '['
expecting ')', '_', alphanumeric character, or operator
```

**Comment by mrkkrp** [comment]
Hi @xhliu, sorry for the long delay with my reply. I'm rather overloaded these days and only now got a chance to go through some open source questions. In order to better understand the setup I clicked to on the link you provide and discovered that you have got an answer on Reddit, so I suppose this issue is good to close.
