### ISSUE TITLE
`manyTill` and `lookAhead`

### ISSUE THREAD

**Issue by drsooch** [mrkkrp/megaparsec#454]
This is more of a question than anything. Hopefully it's the right place to ask. In the "endpoint" for `manyTill` I want to stop when I reach specific token. As it stands, using a bare parser (i.e. no lookahead) will consume the specific token to stop at. However, I want to parse that token _after_ `manyTill` stops. 

For example, `manyTill pStatements pLabel`. I need the label to continue. I started using `lookAhead` as in `manyTill pStatements (lookAhead pLabel)` However, I'm confused on what it means in the documentation when it says:

> If p fails, lookAhead has no effect, i.e. it will fail consuming input if p fails consuming input. Combine with try if this is undesirable.  

 If I'm understanding this correctly, if the lookAhead fails, it consumes input? From limited testing that's what it appears to be doing. Is there another way to do `manyTill` that doesn't consume input on the stop parser?

**Comment by mrkkrp** [comment]
What you are doing sounds okay to me:

```haskell
manyTill pStatement (lookAhead pLabel)
```

`lookAhead` just modifies how `pLabel` behaves when it succeeds—it does not consume any input in that case. If `pLabel` fails, then both `lookAhead pLabel` and `pLabel` behave identically. This is what the documentation tries to convey.

Obviously `manyTill` is going to try to run `pLabel` regularly, otherwise it would not know where to stop. If `pLabel` is actually a complex composite parser, then `lookAhead pLabel` may be not enough because you want the parser to backtrack on failure. To accomplish that try `lookAhead (try pLabel)`.

Hope this helps.

**Comment by drsooch** [comment]
Appreciate it. I think I was misinterpreting what the documentation was saying.
