### ISSUE TITLE
Combinator 'many' is applied to a parser that accepts an empty string.

### ISSUE THREAD

**Issue by erikd** [mrkkrp/megaparsec#48]
I've written a simple parser and while testing it I get the above `ErrorCall` even though I am not using the `many` combinator directly. Someone on IRC suggested that I'm getting this error because the `some` combinator uses `many` under the hood.

I find this behaviour rather unexpected.

**Comment by erikd** [comment]
I've now removed all uses of the `some` combinator and all of my uses of `many` are on parsers that consume at least one `Char` and I'm still getting this error.

**Comment by erikd** [comment]
Ok, turned out I was doing:

```!hs
pLexeme = L.lexeme (P.some (P.char ' '))
```

and changing it to:

```!hs
pLexeme = L.lexeme (P.satisfy (== ' '))
```

sorted it out.

**Comment by mrkkrp** [comment]
@erikd, Assuming that `P` standard for `Text.Megaparsec` or something equivalent, I don't see how

```haskell
L.lexeme (P.some (P.char ' '))
```

could lead to this exception, since even although `some` is indeed defined in terms of `many` (that's standard definition and that error is rather a red flag for your as programmer, that's not something that gets to your users), `char ' '` does not accept empty strings.

Can you describe how to reproduce your original problem step by step?

**Comment by mrkkrp** [comment]
@erikd, Also note that `P.satisfy (== ' ')` will pick up only one space character, while `P.some (P.char ' ')` can parse many of them (without problems!). If you can show how exactly you got this message it will be much easier for me to point out the best solution for your and explain why you get this results.

(You usually always should include code snippet that can be used to reproduce problem in this sort of issue.)

**Comment by mrkkrp** [comment]
By the way `satisfy (== <single char>)` is always better written as `char <single char>`. This way you get better messages too. `char` is defined as:

```haskell
char c = satisfy (== c) <?> showToken c
```

**Comment by erikd** [comment]
I managed to get past that problem and have little recollection of what it was. Closing this.
