### ISSUE TITLE
What about an indent parser?

### ISSUE THREAD

**Issue by minad** [mrkkrp/megaparsec#54]
Hi Mark,

is this still planned?

Daniel

**Comment by mrkkrp** [comment]
Released version of Megaparsec should be able to help with parsing of indentation-sensitive languages. Decent tutorial is not yet written, but I guess it will be written, check https://mrkkrp.github.io/megaparsec/ later. We mainly work now on compatibility with older versions of GHC (done) and Megaparsec's site and tutorials.

Take a look at [Text.Megaparsec.Lexer](https://hackage.haskell.org/package/megaparsec-4.0.0/docs/Text-Megaparsec-Lexer.html), it provides two essential things that allow you work with indentation-sensitive grammars: you can control what is consumed after every lexeme automatically. I.e. you can control whether newline should be consumed or not on per-lexeme basis. Another helper is [`indentGuard`](https://hackage.haskell.org/package/megaparsec-4.0.0/docs/Text-Megaparsec-Lexer.html#v:indentGuard). From its documentation:

> `indentGuard spaceConsumer test` first consumes all white space (indentation) with `spaceConsumer` parser, then it checks column position. It should satisfy supplied predicate `test`, otherwise the parser fails with error message “incorrect indentation”. On success current column position is returned.

> When you want to parse block of indentation first run this parser with predicate like `(> 1)` — this will make sure you have some indentation. Use returned value to check indentation on every subsequent line according to syntax of your language.

In simple cases you can explicitly pass around value returned by `indentGuard`, i.e. current level of indentation. If you prefer to preserve some sort of state you can achieve backtracking state combining `StateT` and `ParsecT`, like this:

```haskell
StateT Int Parser a
```

↑ Here we have state of type `Int`. You can use `get` and `put` as usual, although it may be better to write modified version of `indentGuard` that could `get` current indentation level (indentation level on previous line), then consume indentation of current line, perform necessary checks, and `put` new level of indentation. On failure it could report “incorrect indentation”.

So, it's up to you, basic tools are at your disposal. If you want to work with state, it's also easy.

**Comment by minad** [comment]
Yes, I've seen the indentGuard. I agree that it is no problem to write it with the currently provided primitives as it was in Parsec. What I am basically asking if you will supply additional helper functions, e.g. like provide an IndentParser which manages the state and something like saveIndent to parse blocks? I pointed to this before in https://github.com/aslatter/parsec/pull/41
There is also https://github.com/sdiehl/write-you-a-haskell/blob/master/chapter9/layout/Layout.hs

**Comment by mrkkrp** [comment]
@minad, so this issue is feature request asking for higher-level tools to parse indentation-sensitive grammars.

Will the tools be added? Right now: no, we have different strategic aims right now (lowering of minimal version of `base` and tutorials). In future: probably yes.

**Comment by minad** [comment]
ok, great work btw :)

**Comment by mrkkrp** [comment]
I started to work on higher-level helpers for indentation-sensitive grammars. The work will live in [`advanced-indent`](https://github.com/mrkkrp/megaparsec/tree/advanced-indent) branch for now.

I've looked into that module from “Write You a Haskell” and also search shows the following implementation for Parsec: [`indents`](https://hackage.haskell.org/package/indents) package. This provides quite a few functions, and adds state monad inside `ParsecT`.

We could easily mimic this approach and be quite successful because we can do it in a bit more abstract way having types like this:

```haskell
foo :: (MonadParsec s m Char, MonadState SourcePos m) => m a
```

But thinking about his problem I wonder if we can build safer and more composable API without introducing additional state. Couldn't we handle this with just function composition (I mean, *composition* in general, not just `(.)`)?  In principle, we have two situations:

* top-level things: no indentation at all (e.g. top-level function definitions);

* indented input.

Indentation levels are always relative. To have indentation you need a “reference indentation level”, thus “reference” token and a collection of indented tokens. In turn, some indented tokens can have their own indented blocks, etc. But the main idea is that there is top-level objects and then indented objects that are eventually are “children” (direct or indirect) of “top-level” objects. Couldn't we just express this all as combination of parsers without introducing state at monad level? I think it's possible.

Let's use `indentGuard` and describe those two cases in Haskell.

```haskell
-- | Parse non-indented construction. This ensures that there is no
-- indentation before actual data. Useful as a wrapper for top-level
-- function definitions, for example.

notIndented :: MonadParsec s m Char
  => m ()              -- ^ How to consume indentation (white space)
  -> m a               -- ^ How to parse actual data
  -> m a
notIndented sc p = indentGuard sc (== 1) *> p

-- | Parse a “reference” token and a number of other tokens that have
-- greater (but the same) level of indentation than that of “reference”
-- token.
--
-- Note that the second argument (function that's used to combine results of
-- parsing of “reference” token and indented tokens) lives in parser monad,
-- this allows to perform additional checks and fail with custom error
-- messages, for example.

withBlock :: MonadParsec s m Char
  => m ()              -- ^ How to consume indentation (white space)
  -> (a -> [b] -> m c) -- ^ How to create output from parsed pieces
  -> m a               -- ^ How to parse “reference” token
  -> m b               -- ^ How to parse indented tokens
  -> m c
withBlock sc f r p = do
  ref <- indentGuard sc (const True)
  a <- r
  b <- many (indentGuard sc (> ref) *> p)
  f a b
```

`withBlock` is similar to that from `indents` package, but it's more powerful. Using these functions, it should be possible to handle most use-cases elegantly. If you need something more complex, you can use `indentGuard` directly.

For example, `notIndented sc (withBlock sc f header bodySt)` can be used to parse top-level function definition in language like Python. `f` is used to combine data from header with statements from body. `bodySt` can in turn use `withBlock` to describe `for` loop or `if` statement, etc. I think this approach can result in greater composability, given that functional programming is mainly about composability, it's a win, IMHO.

Maybe I'm too naive right now, but I don't see problems with this approach so far, all stateful info we need is already built-in in parser monad and explicitly tying “reference” token with group of indented tokens gives us all information we need without additional state.

**Comment by mrkkrp** [comment]
Better name and more correct implementation:

```haskell
indentBlock sc f r p = do
  ref   <- indentGuard sc (const True)
  a     <- r
  level <- indentGuard sc (> ref)
  b     <- sepBy p (indentGuard sc (== level))
  f a b
```

**Comment by mrkkrp** [comment]
OK, this is a bit more hairy in implementation than those snippets, but the idea itself seems to be correct.

*Note to self: we need a tutorial explaining how to parse indentation-sensitive languages once new combinators are ready.*

**Comment by nd2s** [comment]
+1, really looking forward to that one. Have been struggling with indented code blocks for the last days.

**Comment by minad** [comment]
@mrkkrp great work, also in general with megaparsec! I don't have time to review or use it right now but I will do so soon. If I find issues then I will let you know!

**Comment by mrkkrp** [comment]
@minad, It's not really ready right now. What's on that branch is not flexible enough. I'm still working on API and tests. Once it's good enough I'll push updates. But given that I'm in rather relaxed winter mood these days, the whole thing may take a week or so :-D

**Comment by minad** [comment]
@mrkkrp Then keep your winter mood, there is no hurry :snowman:

**Comment by mrkkrp** [comment]
So this seems to be usable now. I'll write a short introductory tutorial and post link to it here. I want to play with this a little before releasing new version of Megaparsec to Hackage, though.

**Comment by mrkkrp** [comment]
Check out [this new tutorial](https://mrkkrp.github.io/megaparsec/tutorials/indentation-sensitive-parsing.html), it should introduce the new features pretty well. Let me know if something can be improved.

**Comment by mrkkrp** [comment]
@nd2s, @minad, are the new combinators helpful? If you're still missing something please open an issue. I myself don't need to parse indentation-sensitive grammars (yet), so I need your input to improve the library in this direction.

**Comment by nd2s** [comment]
Sorry I haven't had time to test yet. Have to finish other features first before I'll try improving my crappy indent parser implementation. I will report once I know more.

**Comment by minad** [comment]
@mrkkrp Hi, I finally had time to take a look at this and play with it. I wonder why you wrote indentBlock with IndentOpt? I might prefer different combinators. Furthermore I need line folding to parse a Haskell like syntax which doesn't seem to be possible yet.

**Comment by mrkkrp** [comment]
@minad, I agree, there are many ways to write `indentBlock`, can you elaborate how you would approach it? Maybe you can propose a better solution and we will change the implementation in Megaparsec 5.0.0.

Line folding will be added in Megaparsec 5.0.0, which is in works right now. Here is [an issue](https://github.com/mrkkrp/megaparsec/issues/87) that requests line folding.

**Comment by minad** [comment]
Hi, I have to admit that for now I switched back to the old LayoutParser with state https://gist.github.com/minad/45535d0be4ba52dd64f285e03b38f8c1 :smile_cat:

**Comment by mrkkrp** [comment]
OK, line-folding is missing, but what's wrong with `identBlock`? It works well IMO and without additional state. Here we have a tutorial:

https://mrkkrp.github.io/megaparsec/tutorials/indentation-sensitive-parsing.html

**Comment by nd2s** [comment]
I'm using it without problems (just waiting for the line folding :) ).

**Comment by minad** [comment]
@mrkkrp I think there is nothing wrong with it - it is really just the linefolding which I need. The other point is that I switched over from Parsec but the code written in the "old style" using the stateful LayoutParser.

**Comment by minad** [comment]
@mrkkrp Btw. I've also seen your tutorials. Great work! Megaparsec is documented much better than most Haskell libraries, I like your style very much :+1:

**Comment by mrkkrp** [comment]
Thank you. I just wanted to make sure that solutions in the library do not suck ;-) If something sucks, I'm always ready to talk about it and to fix it. Feedback from users, descriptions of real practical difficulties help improve the project a lot.
