### ISSUE TITLE
Support parsing and processing of line pragmas

### ISSUE THREAD

**Issue by Toxaris** [mrkkrp/megaparsec#55]
I often write parsers for the small languages that come up in my PL research, and when it's time to write a paper, I like to use [`lhs2tex --newcode`](http://www.andres-loeh.de/lhs2tex/) to extract the source code of examples from my `*.tex` sources for automatic checking. I want the error messages to point to my `*.tex` file, not the generated file, so I have to add support for `{-# LINE ... #-}` pragmas to my parser. For example, see [this commit](https://github.com/tewe/uroboro/commit/c9c40c5c4b8908b5890f7a116640f778e7443ec5).

While the implementation is not overly hard, it requires me to drop to a relatively low level of abstraction. I would appreciate a more high-level API for parsing and processing line pragmas.

**Comment by mrkkrp** [comment]
Right now it looks like this is

* project-specific (have you seen such a feature in any other library of this sort?);

* easy to implement.

So I guess it falls into the category of things that should be done by author of concrete project, not provided by library.

Do you know that Megaparsec has different approach when it comes to parsing of languages? Instead of exceptionally inflexible `Text.Parsec.Token` we have [`Text.Megaparsec.Lexer`](https://hackage.haskell.org/package/megaparsec-4.0.0/docs/Text-Megaparsec-Lexer.html).

This module doesn't lock you into any sort of parsing strategy and doesn't impose anything. One good thing about it is that you can control what white space is on per-lexeme basis. The module provides `space` function which constructs parser that consumes white space. It looks like this:

```haskell
space :: MonadParsec s m Char
      => m () -- ^ A parser for a space character (e.g. 'C.spaceChar')
      -> m () -- ^ A parser for a line comment (e.g. 'skipLineComment')
      -> m () -- ^ A parser for a block comment (e.g. 'skipBlockComment')
      -> m ()
space ch line block = hidden . skipMany $ choice [ch, line, block]
```

This parser (or other parser if needed) is used to define `lexeme` and other functions. From conceptual point of view, `space` defines what is considered white space. The function itself is a helper, you can write your own variation that also takes pragmas in consideration, that's quite easy. This way you won't have to work on lower level of abstraction often.

You can then use something like `WriterT` in combination with `ParsecT` to accumulate encountered pragmas. You can wrap `ParsecT` in `WriteT` if you want backtracking `WriterT` (all tools in Megaparsec work with any instance of `MonadParsec`, not only `ParsecT`, and `WriterT` is instance of `MonadParsec` out of box, so it's all easy).

I don't see reason to include this sort of feature right now, closing. Feel free to comment if you think I'm mistaken.

**Comment by Toxaris** [comment]
Yes I understand that this sort of thing is already easier in megaparsec than in parsec. That's why I'm excited about megaparsec :)

I posted this feature request because the megaparsec announcement on the haskell-cafe mailing list said:

~~~
If you ever had any ideas about what Parsec should've done differently, or
what amazing new combinators it should include, etc., post your ideas here:

    https://github.com/mrkkrp/megaparsec/issues
~~~

**Comment by mrkkrp** [comment]
@Toxaris, Yes, thank you, it's absolutely OK! Actually, when I started to work on Megaparsec I studied all existing issues of Parsec (on GitHub and elsewhere) to find out what should be improved (later, but before initial release, some people began to come here and open issues — that improved the project a lot). I think Megaparsec is hopefully a bit better than Parsec mostly because there are people, active users, who express their opinions on what can be improved.

**Comment by Toxaris** [comment]
Ok great :) Note that `{-# LINE ... #-}` pragmas are harder to support than other pragmas because they have to use something like `setPosition` so that syntax errors after the pragma are reported correctly. So the idea of just collecting all pragmas to be handled later is not sufficient here. On the other hand, `{-# LINE ... #-}` pragmas are also easier to support *generically* than other pragmas because using `setPosition` is often the only thing they need to do, independently of what language you're parsing.
