### ISSUE TITLE
obsolet char and notChar in Tutorial

### ISSUE THREAD

**Issue by maxigit** [mrkkrp/megaparsec#562]
I've just migrated one of my project from Parsec to Megaparsec after reading the tutorial wich is great.
However I noticed that it mentioned `char` and `notChar` which I understand now have been renamed to `anySingle'  `anySingleBut`.
It took me a little while to figure it out so I thought It might be worth mentionning.

**Comment by mrkkrp** [comment]
Thanks! I've just pushed https://github.com/mrkkrp/markkarpov.com/commit/5380c0e46e80491d03add5d740c2cc072a549aec, which fixes what seems to be the only place where `notChar` is still mentioned. As for `char` it is still around in `Text.Megaparsec.Char` (not re-exported by default from `Text.Megaparsec` since you could parse either binary streams or streams of characters).
