### ISSUE TITLE
Having trouble with `makeExprParser`

### ISSUE THREAD

**Issue by echatav** [mrkkrp/megaparsec#59]
Hi, I'm having trouble with a SQL parser using megaparsec. When I parse "SELECT DISTINCT db.stuff.id FROM stuff WHERE id = 1" it works but when I parse "SELECT DISTINCT db.stuff.id FROM stuff WHERE id = 1 ORDER BY id, name ASC LIMIT 20" it errors:

```
> parse query "" "SELECT DISTINCT db.stuff.id FROM stuff WHERE id = 1 ORDER BY id, name ASC LIMIT 20"
Left line 1, column 53:
unexpected 'O'
expecting '%' or white space
```

`%` is the first operator in my expression parser

```
expression :: Parsec String Expression
expression = label "expression" $ makeExprParser term operators
  where
    term = ...
    operators =
      [ [ InfixN $ (ExpressionOPERATION .: OperationMOD) <$ sqltoken "%" ]
      , ...
      ]
```

It's kind of weird that the error refers to only the first operator in the operator table. How do I get this to work? Sorry, not very experienced with parsing libraries.

**Comment by mrkkrp** [comment]
Well, `makeExprParser` is wrong tool for this job. It's written with arithmetic expressions (and the like) in mind, where you have associativity, precedence, fixity.

The language of SQL queries is just a language on its own (and its authors tried to make it look like English, IMHO, so it makes parsing more difficult), with quite specific syntax. In order to parse SQL queries you will probably need [`Text.Megaparsec.Lexer`](https://hackage.haskell.org/package/megaparsec/docs/Text-Megaparsec-Lexer.html) module.

Start with basic structure of SQL queries, they have `SELECT`, `FROM`, `WHERE`, `ORDER BY`, etc. parts that go in specific order and some of them can be omitted. Start designing from top to bottom manner, once you have parser that takes into account all possible clauses of SQL query (BTW, syntax differs a bit between concrete data base implementations), you can start flesh every single clause. At this point I would want to have standardized description of syntax of every clause. There is no “easy” solution, you will have to write parser using available combinators with help of `Text.Megaparsec.Lexer`.

Writing of data structures for abstract syntax tree is good starting point in my opinion, since it will give you firm understanding what can be found in every part of SQL query.

Complete parser of SQL queries may take a bit of time to finish, maybe a few days.

**Comment by echatav** [comment]
Thanks for taking the time to answer my question! To clarify, I'm only using `mkExprParser` for parsing arithmetic (and logical) subexpressions, not all query expressions. In this case, it's only being used on the `id = 1` bit.

**Comment by mrkkrp** [comment]
@echatav, Sorry it was not absolutely clear from what you posted. Obviously expression parser should only consume `1` in this case, but it tries to parse the word `ORDER` as operator, so you get this error message.

Information you provide is not enough to diagnose what's wrong, you need to should how your parser is defined, how `term` is defined, what's in operator table.

As an example, you can load `tests/Expr.hs` into GHCi, to see how expression parser normally work, it may be helpful. Here is what I get:

```haskell
Hours of hacking await!
λ> parseTest expr "1 + 2"
Sum (Val 1) (Val 2)
λ> parseTest expr "1" -- ← this is your case (equals sign shouldn't be
                      -- parsed in expression parser in your case)
Val 1
λ> parseTest expr "1 O" -- ← here I added letter “O”, normally expression
                        -- parser just stops when it encounters something it
                        -- cannot parse, at this point you just pick up
                        -- “ORDER BY” part, etc.
Val 1
λ> parseTest (expr <* eof) "1 O" -- here I added ‘eof’ parser to force parse
                                 -- error
1:3:
unexpected 'O'
expecting end of input, operator, or rest of expression
-- if I remove ‘<?> "expression"’ part, I get even better results:
λ> parseTest (expr <* eof) "1 O"
1:3:
unexpected 'O'
expecting end of input or operator
```

So, it's difficult to tell why you're getting this result. Actually every operator is `label`ed in source code of `Text.Megaparsec.Expr` and should be reported as “operator”. Do you have multicharacter operators? If so, see in [documentation for `makeExprParser`](https://hackage.haskell.org/package/megaparsec/docs/Text-Megaparsec-Expr.html#v:makeExprParser):

> Please note that multi-character operators should use 'try' in order to be reported correctly in error messages.

Hope it helps.

**Comment by mrkkrp** [comment]
Closing for now due to lack of input.

**Comment by echatav** [comment]
Hi, sorry for the delayed response but I got sidetracked and haven't been able to go back to this problem for a couple days. I really appreciate the help though!
