### ISSUE TITLE
The sepEndBy implementation is wrong

### ISSUE THREAD

**Issue by bartavelle** [mrkkrp/megaparsec#63]
This is wrong:

    sepEndBy p sep = sepBy p sep <* optional sep

This works as expected:

    > parse (string "hello" `sepBy` char ',' <* optional (char ',')) "test" ("hello,hello" :: String)
    Right ["hello","hello"]

This doesn't:

    > parse (string "hello" `sepBy` char ',' <* optional (char ',')) "test" ("hello,hello," :: String)
    Left test:1:13:
    unexpected end of input
    expecting "hello"

The parsec implementation is correct though.

**Comment by bartavelle** [comment]
Also as a side note I do use the `sepEndBy1` and `sepEndBy` combinators a lot, and I don't see how this is helpful to deprecate them as I will have to rewrite them myself anyway ... but perhaps this is just me.

**Comment by mrkkrp** [comment]
Thanks for this report, this will be fixed in a couple of days and hotfixed Megaparsec 4.1.1 will be released. Since you claim you use the combinators a lot and my definition turns out to be wrong, I'll remove deprecation notes from these two functions.

It was my fault because I considered the functions easily replaceable by that definition involving `optional` (which looked so good so none of us actually tested it). There were no tests written for the deprecated functions. Now I'll write the missing tests to ensure correctness of the new implementations.

**Comment by bartavelle** [comment]
I thought it looked good too. I realized it didn't work as expected only when the parsing started to fail !

As for the real world use of these combinators, *I* use them a lot because I work with puppet files. I don't know how common such constructions are ...

**Comment by mrkkrp** [comment]
@bartavelle, Megaparsec 4.1.1 is on Hackage now with this stuff fixed.

**Comment by bartavelle** [comment]
Awesome thanks !
