### ISSUE TITLE
notFollowedBy combinator does not use correct failure message (I think)

### ISSUE THREAD

**Issue by recursion-ninja** [mrkkrp/megaparsec#68]
On a failure of the `notFollowedBy` combinator (success of the parameter cambinator) a generic error message is shown rather then the error message for the parameter combinator.

**Example:**

    let commentStart = string "{-" <?> "comment start"
        commentEnd   = string "-}" <?> "comment end"
        combinator   = notFollowedBy $ commentStart <|> commentEnd
    in parse combinator "" "{-"

**Expected:**

    Left line 1, column 1:
    unexpected comment start

**Actual:**

    Left line 1, column 1:
    unexpected '{'

I think that this behavior is unexpected as I would have expected the former output rather then the latter. Is the current error message of `notFollowedBy` incorrect/unexpected or is it reporting errors as intended?

**Comment by mrkkrp** [comment]
@recursion-ninja, this is consequence of how Megaparsec and Parsec `label` combinator work. When you wrap some parser `p` with `label` you're adding additional processing when `p` fails (that is, when it calls a continuation corresponding to failure). In this case `label` can replace default error message with something else or remove it altogether.

If your parser doesn't fail (as in your case), the corresponding continuation is never called and it's not possible to know what label has been associated with your parser, if any. So when `notFollowedBy` needs to report something, it has just succeeded parser (all information we have about this parser is its result), so we need a fallback here. Most reasonable fallback is to extract the next token (character) from stream and report it as something unexpected. If the stream is empty, then obviously we have unexpected end of input:

```haskell
pNotFollowedBy :: Stream s t => ParsecT s m a -> ParsecT s m ()
pNotFollowedBy p = ParsecT $ \s@(State input pos _) _ _ eok eerr ->
  let l = maybe eoi (showToken . fst) (uncons input)
      cok' _ _ _ = eerr $ unexpectedErr l pos
      cerr'    _ = eok () s mempty
      eok' _ _ _ = eerr $ unexpectedErr l pos
      eerr'    _ = eok () s mempty
  in unParser p s cok' cerr' eok' eerr'
```

Here if target parser `p` succeeds it calls `cok'` or `eok'` and these functions use `l` to report the error as I described, you can see for yourself that no information about `label` is available at this point.

Parsec uses a bit different approach, it takes result of succeeded parser, then plainly renders it into string with `show` and uses that. This is very wrong, IMHO, because you generally don't know what sort of thing you've just parsed and how it will be presented in error message. Also, Megaparsec uses special pretty-printing implemented in `ShowToken` type class that Parsec's approach would ruin some nice features we have.

So, no, I don't consider this unexpected result.

**Comment by recursion-ninja** [comment]
I tried tinkering with the parser primitives and I couldn't find a way to make it work either. I think you might be correct, that it is impossible. I had tried to define `cok'` and `eok'` in terms of `p` in `pNotFollowedBy` to get the error message associated with the parameter combinator on a failure, but that didn't work...

**Comment by mrkkrp** [comment]
I'm telling you for sure, it's not possible. For `p <?> l` to be reported as `l`, it should fail. Since `p` doesn't fail by definition when `notFollowedBy` fails, we have no way to know `l`.

I understand that this may be disappointing, but `label` (and `<?>`) does not create any sort of attached label. (Maybe the name of the combinator is a bit misleading.)

**Comment by recursion-ninja** [comment]
That was my initial assumption, that `label` had altered the combinator and "injected" a different error message within the original. I see now in the primitive definitions that that is not the case. I guess the impossible is just impossible :(

Thanks for the detailed explanation though, I appreciate it!
