### ISSUE TITLE
Combinators like Data.Attoparsec.Bytestring missing

### ISSUE THREAD

**Issue by benma** [mrkkrp/megaparsec#74]
Hi

I wanted to parse a ByteString and match ByteStrings etc., but in Text.Megaparsec.ByteString, there are no combinators to make it easier, i.e. a `string` combinators that returns a ByteString.

It would be nice to add the combinators from [attoparsec](https://hackage.haskell.org/package/attoparsec-0.13.0.1/docs/Data-Attoparsec-ByteString.html).

Are there any plans for this?

**Comment by mrkkrp** [comment]
@benma, Megaparsec can parse `ByteString`s just fine. Module `Text.Megaparsec.ByteString` just provides a synonym `Parser`,

```haskell
type Parser = Parsec ByteString
```

you see, there is no much specialization in that module because the whole library already works with different input streams (it works with any instance of `Stream`).

Megaparsec takes `String`s as arguments and returns parsed `String`s because unlike Attoparsec, which can only parse *strict* `ByteString`s, Megaparsec can work with:

* `String` = `[Char]`

* `ByteString` (strict and lazy)

* `Text` (strict and lazy)

That's 5 five different types of input stream we should handle, so we need a “common denominator” type in some cases (which could be in theory polymorphic, but the effort doesn't worth it), which is historically `String`. In combinators like `string`, those strings are usually not very long, and since they are consumed from head to tail, list structure of `String`s is not that bad in this case.

I don't see any problem with current approach, so to answer your question, there is no plans to make Megaparsec take something different as arguments of some combinators (it would also break users' code).

**Comment by mrkkrp** [comment]
In fact there are modules in Attoparsec now which can work with `Text` and they take `Text` as arguments for example, but note that it's completely different module with different code (which is the right thing given Attoparsec's focus on performance). Megaparsec is not primarily about speed but about features and flexibility, so we choose to have single code-base that can work with different types of strings.

**Comment by benma** [comment]
Thanks for the quick response.

I see the point of `string` being used with small strings only.

What if I have a huge ByteString, and I want to get the next `n` bytes as a ByteString, where `n` is large?

something like `takeByteString n` from attoparsec.

My current problem involves going through a big text file, and reprinting most of it as is until a certain keyword appears, where the real parsing starts. Then the whole thing repeats many times.

**Comment by mrkkrp** [comment]
Well, first of all if you have actual text, why not to deal with it as `Text`, not `ByteString`?

Another thing to note is that since most part of your big file shouldn't parsed, you can leverage the fact that Megaparsec supports incremental parsing (something that's missing in Parsec). This means that you can search where actual work for Megaparsec begins and use something like `runParser'` to start parsing from the middle of the file. You can also supply initial textual position (line, column), so it's displayed in error messages properly.

If your file is *really* big and speed matters Attoparsec may be a better choice. Megaparsec is usually good for source code and the like, when size of input is usually not very big, but error messages are important.

**Comment by benma** [comment]
It is not Text, it is a ByteString, though with Text I would have the same issue.

I could do what you suggest, but since the whole thing repeats zero or more times, I would like to do everything inside Megaparsec, sth. along the lines of `many (skipTillString >> doSomething)`. I want to avoid building manual plumbing to seek and jump to a place repeatedly.

Thanks anyway for the suggestions, I appreciate it.
