### ISSUE TITLE
Support error recovery

### ISSUE THREAD

**Issue by adamwalker** [mrkkrp/megaparsec#80]
I frequently want the parsers I write that accept human input to be able to recover from errors and continue parsing if possible.

In this commit: https://github.com/adamwalker/megaparsec/commit/e005dec57c5faf180846fced1cd262f124c18083 I hacked together basic support for error recovery into Megaparsec in two functions: "recover" and "recoverNoBacktrack" with identical signatures:

```
 recoverNoBacktrack :: ParsecT s m a -> (ParseError -> ParsecT s m a) -> ParsecT s m a 
```

For example, this allows you to write:
```
recoverNoBacktrack parseCStatement $ \err -> manyTill (satisfy (const True)) (symbol ";")
```

Which will, on encountering an error parsing the C statement, skip characters from where the error was encountered until a synchronizing semicolon is reached. 

You can also save the "err" argument, for example using the state monad, and present a list of errors to the user when parsing is done.

Is this something you consider worthwhile having in Megaparsec? If so, I will clean up my commit and submit a PR.

**Comment by mrkkrp** [comment]
This is definitely a useful thing. I haven't looked in detail how you did it, but I will. Right away I can say that it would be good if this feature had no impact on performance of parsers that do not use it. This will need to be tested.

Another idea that comes to mind is that something like this can be achieved without hooking into internals of Megaparsec like this:

```haskell
maybeCStmt = (Just <$> try parseCStmt) <|> (Nothing <$ skipTill (symbol ";"))
  where skipTill = manyTill anyChar
```

Here, if a statement is malformed we will get `Nothing`, otherwise we will get parsed statement in `Just`. In the both cases we will be able to continue parsing. The only problem here is that we cannot get error message for malformed statement, but this can be done too in principle.

**Comment by adamwalker** [comment]
That is exactly how my "recover" function works. It is just "<|>" but it gives the ParseError to the second argument. I doubt this will have any impact on performance. 

The "recoverNoBacktrack" function is more complex, however, as the second argument resumes parsing where the frst one encountered the error. I had to modify ParsecT to make the consumed-error continuation take a State argument to do this. 

This might have an impact on performance. However, I found that starting error recovery from the error location and not backtracking to the start of the parseCStmt was much easier. If you backtrack and you're not careful and another synchronizing token occurs between the start of the C statement and the error, then you end up synchronizing before your original error. 

As an example of where this happens, consider parsing a C statement:
```
maybeCStmt = (Just <$> try parseCStmt) <|> (Nothing <$ skipTill (symbol ";" <|> lookahead startOfCStatement)
    where skipTill = manyTill anyChar
```
where I also resynchronize where I see something that looks like another C statement. This allows you to synchronize even in the case of a missing semicolon. 

However, this parser will actually loop forever when there is an error because the "try" backtracks to the start of the original C statement, it synchronizes immediately, hits the same error, and loops again.

I guess there are ways around this, but I found it a lot easier to get it right without backtracking because, unless the error occurs on the first token, the parser is guaranteed to make some forward progress.

**Comment by mrkkrp** [comment]
OK, here is what I think:

1. Definitely useful feature that most likely will be in Megaparsec.

2. Only variant without backtracking should be added. The version with backtracking, as you point out, does not quite cut it — it's rather half-solution.

3. About naming: `recover` is short, but it's imperative form — not very good for a function that is a wrapper that changes behavior in some way. I think `recovering`, `withRecovering`, or `withRecovery` are better.

4. Finally about implementation. As you probably know, unlike Parsec, we have a type class `MonadParsec` which includes all fundamental primitives. This allows to put `ParsecT` *inside* other monads like `StateT`. This new function should be method of `MonadParsec` type class.

5. I believe that we should not add `State` as argument of `cerr` continuation, but instead include state information into `ParseError` itself. It already contains part of it, now it's time to include everything. This will also improve how `runParsecT` and consequently functions related to incremental parsing (`runParserT'` and `runParser'`) work — they will be able to return more actual state information on failure (for now they are rather misleading in these cases). I'm not entirely sure about this. Passing around state may be a better idea in that it won't break compatibility. Then perhaps we should pass it in `eerr` continuation too, because some parsers can change parser state without consuming input (see `stateTabWidth`).

Once 5 is done, this new feature will be trivial to implement without touching other code. When I have more time to spend with Megaparsec, I will implement these things. I'll also check how it affects performance. After that I will ping you, and you will be able to easily put together a PR using the new features.

**Comment by adamwalker** [comment]
Great, thanks for looking at it. I agree with all that you said. 

99% of the work is in (5). Actually adding the recovering function is almost trivial. I don't mind if you do that too (though I'm perfectly happy to do it if you want).

**Comment by mrkkrp** [comment]
Here is the thing: #86. FYI, the recovering parser (which is sort of “plan B” anyway) should not influence error messages in any way or it will lead to very confusing messages in some cases. Another thing that I did differently is handling of failure of recovering parser. Again, it would be quite confusing for end-user to see error message of recovering parser, so in my solution when recovering parser fails, user just gets original error message (which main parser produced) as if no `withRecovery` combinator is used.

**Comment by adamwalker** [comment]
That commit looks good. I'll have a play with it on the weekend and see if it behaves as expected. 

Thanks.

**Comment by adamwalker** [comment]
I tried it out and it works perfectly.
Thanks

**Comment by mrkkrp** [comment]
It's now in Megaparsec. 4.4.0 will be released in a couple of days. Thanks for this feature-request!

**Comment by adamwalker** [comment]
You're welcome. Thanks for the implementation!

**Comment by mrkkrp** [comment]
FYI, now there is even a tutorial demonstrating the feature:

https://mrkkrp.github.io/megaparsec/tutorials/fun-with-the-recovery-feature.html
