### ISSUE TITLE
Parse block of text including whitespaces

### ISSUE THREAD

**Issue by nd2s** [mrkkrp/megaparsec#87]
I need to parse something like this:

    header
        SELECT *
        FROM table
            WHERE x=1

into a tuple `(String, String) == ("header", "SELECT *\nFROM table\n    WHERE x=1")`. I think current implementation can't do that because It will always try to parse as many whitespace characters as possible, and throw an error if there are more.

This concrete problem would be solvable with line-folding (which isn't implemented yet), and then `concat`ing all the lines, because spaces + newlines don't matter in SQL.

But there are cases where preserving whitespaces is important. If instead of SQL we'd wanted to parse Python for example.

Would it make sense to offer a function/mode that only throws an error if indentation is too small?

*Edit*: There were supposed to be 4 whitespaces before "WHERE" in the result string. Github seems to merge them into one.

**Comment by mrkkrp** [comment]
This can be done with current versions of Megaparsec, but not in most elegant way. As you pointed out, the item under `header` is line-folded. Once the feature is added to Megaparsec (probably in version 5.0.0), this should be quite easy to handle.

**Comment by mrkkrp** [comment]
I'll keep this issue as feature-request for line-folds.

**Comment by mrkkrp** [comment]
The line folding functionality is now implemented, although this particular case does not need it because you don't parse line-folded expression (to AST or something), you want to just grab it. So here is how to do it (with current version of Megaparsec):

```haskell
-- | This may not compile, no time to check, sorry, but idea should be
-- clear.

scn :: Parser ()
scn = space spaceChar empty empty

myParser :: Parser (String, String)
myParser = (,)
  <$> nonIndented header
  <*> manyTill anyChar (indentGuard scn (== 1))
  where header = symbol scn $ (:) <$> letterChar <*> alphaNumChar
```

The idea is to grab all chars until you get indentation level equal to one. This last part may require checking if we got to end of file as well, hope you can figure it out in the process.

You can take a look at the new `lineFold` function as well, if you're interested.
